import { LockKeyhole } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { ApiError } from '../../../api/client'
import { useAuth } from './AuthProvider'

export function PasswordChangePage() {
  const { changePassword, logout } = useAuth(); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [done, setDone] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (newPassword !== confirmation) { setError('As novas senhas não coincidem.'); return } try { await changePassword(currentPassword, newPassword); setDone(true) } catch (e) { setError(e instanceof ApiError ? e.message : 'Não foi possível alterar a senha.') } }
  if (done) return <main className="login-page"><section className="login-card"><div className="login-heading"><span className="eyebrow">Senha atualizada</span><h1>Acesso liberado</h1><p>Sua senha foi alterada com sucesso.</p></div><button className="login-button" type="button" onClick={() => window.location.reload()}>Continuar</button></section></main>
  return <main className="login-page"><section className="login-card"><div className="login-heading"><span className="eyebrow">Primeiro acesso</span><h1>Troque sua senha</h1><p>Por segurança, defina uma nova senha antes de continuar.</p></div><form className="login-form" onSubmit={submit}><label><span>Senha atual</span><div className="input-field"><LockKeyhole size={18} /><input type="password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} required /></div></label><label><span>Nova senha</span><div className="input-field"><LockKeyhole size={18} /><input type="password" minLength={12} value={newPassword} onChange={e => setNewPassword(e.target.value)} required /></div></label><label><span>Confirme a nova senha</span><div className="input-field"><LockKeyhole size={18} /><input type="password" minLength={12} value={confirmation} onChange={e => setConfirmation(e.target.value)} required /></div></label>{error && <div className="form-error" role="alert">{error}</div>}<button className="login-button" type="submit">Alterar senha</button><button className="text-button" type="button" onClick={logout}>Sair</button></form></section></main>
}
