// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
import { resolveFinancialResponsibleMemberId } from '../members/domain.js'

const serialize = (charge: any) => ({ ...charge, amount: Number(charge.amount), payments: charge.payments?.map((p: any) => ({ ...p, amount: Number(p.amount) })) ?? [] })
const effectiveStatus = (charge: any) => charge.status === 'PENDING' && new Date(charge.dueDate) < new Date() ? 'OVERDUE' : charge.status
const chargeInclude = { member: { include: { person: true, category: true, titular: { include: { person: true } } } }, responsibleMember: { include: { person: true } }, payments: { orderBy: { paidAt: 'desc' }, include: { registeredBy: { select: { id: true, person: { select: { fullName: true } } } } } } }

export const financeRoutes: FastifyPluginAsync = async (app) => {
  app.get('/member/me/finance', { preHandler: app.authenticate }, async (request: any, reply) => {
    const user = await prisma.user.findUnique({ where: { id: request.authUser.id }, include: { person: { include: { member: true } } } })
    if (!user?.person.member) return reply.code(403).send({ message: 'Área disponível apenas para associados.' })
    const responsibleId = await resolveFinancialResponsibleMemberId(user.person.member.id)
    const charges = await prisma.financialCharge.findMany({ where: { responsibleMemberId: responsibleId ?? undefined }, include: { payments: true }, orderBy: { dueDate: 'desc' } })
    const rows = charges.map((c) => ({ ...serialize(c), status: effectiveStatus(c) }))
    return { responsible: user.person.member.titularMemberId ? { memberId: responsibleId } : { memberId: user.person.member.id }, status: rows.some((c) => c.status === 'OVERDUE') ? 'OVERDUE' : rows.some((c) => c.status === 'PENDING') ? 'PENDING' : 'PAID', history: rows }
  })
  app.get('/finance/charges', { preHandler: app.requirePermission('finance.view') }, async (request: any) => { const rows = await prisma.financialCharge.findMany({ where: request.query?.status ? { status: request.query.status } : undefined, include: chargeInclude, orderBy: { dueDate: 'desc' } }); return rows.map((c) => ({ ...serialize(c), status: effectiveStatus(c), member: { ...c.member, person: { ...c.member.person, cpfMasked: `${c.member.person.cpf.slice(0, 3)}.***.***-**` } } })) })
  app.get('/finance/dashboard', { preHandler: app.requirePermission('finance.view') }, async (request: any) => { const from = request.query?.from ? new Date(request.query.from) : new Date(new Date().getFullYear(), 0, 1); const to = request.query?.to ? new Date(`${request.query.to}T23:59:59.999Z`) : new Date(); const charges = await prisma.financialCharge.findMany({ include: { payments: true, responsibleMember: { include: { person: true } } } }); const active = charges.filter((c) => c.status !== 'CANCELLED'); const overdue = active.filter((c) => effectiveStatus(c) === 'OVERDUE'); const payments = active.flatMap((c) => c.payments).filter((p) => new Date(p.paidAt) >= from && new Date(p.paidAt) <= to); const pending = active.filter((c) => ['PENDING', 'OVERDUE'].includes(effectiveStatus(c))); const byDay = new Map<string, number>(); for (const p of payments) { const day = new Date(p.paidAt).toISOString().slice(0, 10); byDay.set(day, (byDay.get(day) || 0) + Number(p.amount)) } return { totalToReceive: pending.reduce((s, c) => s + Number(c.amount), 0), totalReceived: payments.reduce((s, p) => s + Number(p.amount), 0), totalOverdue: overdue.reduce((s, c) => s + Number(c.amount), 0), membersWithPending: new Set(pending.map((c) => c.responsibleMemberId)).size, receivedByDay: [...byDay].map(([date, total]) => ({ date, total })), nextDue: pending.sort((a, b) => +new Date(a.dueDate) - +new Date(b.dueDate)).slice(0, 10).map(serialize) } })
  app.post('/finance/charges', { preHandler: app.requirePermission('finance.manage') }, async (request: any, reply) => { const b = request.body ?? {}; const responsible = await resolveFinancialResponsibleMemberId(b.memberId); if (!responsible) return reply.code(400).send({ message: 'Associado inválido.' }); return reply.code(201).send(await prisma.financialCharge.create({ data: { memberId: b.memberId, responsibleMemberId: responsible, type: b.type || 'OTHER', description: b.description, referenceYear: b.referenceYear ?? null, amount: b.amount, dueDate: new Date(b.dueDate), status: b.status || 'PENDING' }, include: chargeInclude })) })
  app.post('/finance/charges/:id/payments', { preHandler: app.requirePermission('finance.manage') }, async (request: any, reply) => { const charge = await prisma.financialCharge.findUnique({ where: { id: request.params.id }, include: { payments: true } }); if (!charge) return reply.code(404).send({ message: 'Cobrança não encontrada.' }); const payment = await prisma.financialPayment.create({ data: { chargeId: charge.id, amount: request.body?.amount ?? charge.amount, paidAt: request.body?.paidAt ? new Date(request.body.paidAt) : new Date(), method: request.body?.method || 'OTHER', notes: request.body?.notes || null, registeredByUserId: request.authUser.id } }); const total = charge.payments.reduce((s, p) => s + Number(p.amount), 0) + Number(payment.amount); if (total >= Number(charge.amount)) await prisma.financialCharge.update({ where: { id: charge.id }, data: { status: 'PAID', paidAt: payment.paidAt } }); return serialize(payment) })
}
