// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
import { normalizeCpf, normalizePhone } from '../auth/normalization.js'
import { createInvitation } from '../visitors/routes.js'
import { expirePastInvitations, getMemberInvitationQuota, parseCivilDate } from '../visitors/quotas.js'

const invitationView = { visitor: { include: { person: true } }, sponsorMember: { include: { person: true, category: true } }, quotaOwnerMember: { include: { person: true } } }
const memberFromAuth = (id: string) => prisma.user.findUnique({ where: { id }, include: { person: { include: { member: { include: { category: true, titular: { include: { person: true, category: true } } } } } } } })
const familyInvitationWhere = (quotaOwnerMemberId: string) => ({ quotaOwnerMemberId })

export const memberAreaRoutes: FastifyPluginAsync = async app => {
  app.get('/member/me', { preHandler: app.authenticate }, async (request, reply) => {
    await expirePastInvitations()
    const user = await prisma.user.findUnique({ where: { id: request.authUser!.id }, include: { person: { include: { member: { include: { category: true, titular: { include: { person: true, category: true, dependentes: { where: { status: { not: 'TERMINATED' } }, include: { person: true, category: true } } } }, dependentes: { where: { status: { not: 'TERMINATED' } }, include: { person: true, category: true } } } } } } } })
    if (!user?.person.member) return reply.code(403).send({ message: 'Área disponível apenas para associados.' })
    const member = user.person.member; const familyTitular = member.titular || member; const relatedMembers = member.titular ? [familyTitular, ...(familyTitular.dependentes || []).filter((item: any) => item.id !== member.id)] : member.dependentes; const quota = await getMemberInvitationQuota(member.id, new Date()); const invitations = await prisma.visitorInvitation.findMany({ where: familyInvitationWhere(quota.quotaOwnerMemberId), include: invitationView, orderBy: { scheduledDate: 'desc' } })
    return { member: { id: member.id, fullName: user.person.fullName, cpf: user.person.cpf, birthDate: user.person.birthDate, phone: user.person.phone, email: user.person.email, city: user.person.city, photoPath: user.person.photoPath, credentialToken: user.person.credentialToken, category: member.category.name, registrationNumber: member.registrationNumber, status: member.status, admissionDate: member.admissionDate }, isDependent: Boolean(member.titularMemberId), dependents: relatedMembers.map((d: any) => ({ id: d.id, fullName: d.person.fullName, cpf: d.person.cpf, birthDate: d.person.birthDate, photoPath: d.person.photoPath, credentialToken: d.person.credentialToken, relationship: d.titularMemberId ? d.relationship : 'Titular', isTitular: !d.titularMemberId, active: d.status === 'ACTIVE' })), invitations, quota }
  })
  app.get('/member/me/invitations/quota', { preHandler: app.authenticate }, async (request: any, reply) => { await expirePastInvitations(); const user = await memberFromAuth(request.authUser!.id); const member = user?.person?.member; if (!member) return reply.code(403).send({ message: 'Área disponível apenas para associados.' }); const requested = parseCivilDate(`${request.query?.year || new Date().getUTCFullYear()}-${String(request.query?.month || new Date().getUTCMonth() + 1).padStart(2, '0')}-01`) || new Date(); const quota = await getMemberInvitationQuota(member.id, requested); return { quota, invitations: await prisma.visitorInvitation.findMany({ where: familyInvitationWhere(quota.quotaOwnerMemberId), include: invitationView, orderBy: { scheduledDate: 'desc' } }) } })
  app.post('/member/me/visitors', { preHandler: app.authenticate }, async (request: any, reply) => { const b = request.body || {}; const fullName = typeof b.fullName === 'string' ? b.fullName.trim() : ''; const cpf = normalizeCpf(b.cpf); const phone = normalizePhone(b.phone); const city = typeof b.city === 'string' ? b.city.trim() : ''; const state = typeof b.state === 'string' ? b.state.trim().toUpperCase() : ''; const validStates = new Set(['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']); if (!fullName) return reply.code(400).send({ message: 'Informe o nome completo.' }); if (!cpf) return reply.code(400).send({ message: 'Informe um CPF válido.' }); if (!phone) return reply.code(400).send({ message: 'Informe o telefone.' }); if (!city) return reply.code(400).send({ message: 'Informe a cidade.' }); if (!validStates.has(state)) return reply.code(400).send({ message: 'Informe uma UF válida.' }); const existing = await prisma.person.findUnique({ where: { cpf }, include: { visitor: true } }); if (existing) { if (!existing.visitor) return reply.code(409).send({ message: 'Já existe uma pessoa associada a este CPF.' }); return prisma.visitor.findUnique({ where: { id: existing.visitor.id }, include: { person: true } }) } const person = await prisma.person.create({ data: { fullName, cpf, phone, email: b.email?.trim().toLowerCase() || null, city, state } }); return reply.code(201).send(await prisma.visitor.create({ data: { personId: person.id }, include: { person: true } })) })
  app.get('/member/me/visitors/search', { preHandler: app.authenticate }, async (request: any) => { const q = String(request.query?.q || '').trim(); if (q.length < 2) return []; const digits = q.replace(/\D/g, ''); return prisma.visitor.findMany({ where: { active: true, blocked: false, OR: [{ person: { fullName: { contains: q, mode: 'insensitive' } } }, ...(digits ? [{ person: { cpf: { contains: digits } } }, { person: { phone: { contains: digits } } }] : [])] }, include: { person: true }, orderBy: { person: { fullName: 'asc' } }, take: 20 }) })
  app.post('/member/me/invitations', { preHandler: app.authenticate }, async (request: any, reply) => { const user = await memberFromAuth(request.authUser!.id); const member = user?.person?.member; if (!member) return reply.code(403).send({ message: 'Área disponível apenas para associados.' }); try { return reply.code(201).send(await prisma.$transaction(tx => createInvitation({ ...request.body, sponsorMemberId: member.id }, tx))) } catch (e: any) { return reply.code(e.statusCode || 500).send({ message: e.message || 'Não foi possível criar o convite.' }) } })
  app.post('/member/me/invitations/:id/cancel', { preHandler: app.authenticate }, async (request: any, reply) => { const user = await memberFromAuth(request.authUser!.id); const member = user?.person?.member; const quota = member ? await getMemberInvitationQuota(member.id, new Date()) : null; const invitation = await prisma.visitorInvitation.findUnique({ where: { id: request.params.id } }); if (!member || !quota?.quotaOwnerMemberId || !invitation || invitation.quotaOwnerMemberId !== quota.quotaOwnerMemberId) return reply.code(404).send({ message: 'Convite não encontrado.' }); if (invitation.status === 'USED') return reply.code(409).send({ message: 'Convite já utilizado não pode ser cancelado.' }); if (invitation.status === 'EXPIRED') return reply.code(409).send({ message: 'Convite expirado não pode ser cancelado.' }); if (invitation.status === 'CANCELLED') return invitation; return prisma.visitorInvitation.update({ where: { id: invitation.id }, data: { status: 'CANCELLED' }, include: invitationView }) })
}
