// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
import { normalizeCpf, normalizePhone } from '../auth/normalization.js'
import { createInvitation } from '../visitors/routes.js'
import { getMemberInvitationQuota, parseCivilDate } from '../visitors/quotas.js'

const invitationView = { visitor: { include: { person: true } }, sponsorMember: { include: { person: true, category: true } } }
const memberFromAuth = (id: string) => prisma.user.findUnique({ where: { id }, include: { person: { include: { member: { include: { category: true } } } } } })
export const memberAreaRoutes: FastifyPluginAsync = async app => {
  app.get('/member/me', { preHandler: app.authenticate }, async (request, reply) => {
    const user = await prisma.user.findUnique({ where: { id: request.authUser!.id }, include: { person: { include: { member: { include: { category: true, dependentes: { where: { status: { not: 'TERMINATED' } }, include: { person: true, category: true } } } } } } } })
    if (!user?.person.member) return reply.code(403).send({ message: 'Área disponível apenas para associados.' })
    const member = user.person.member; const quota = await getMemberInvitationQuota(member.id, new Date()); const invitations = await prisma.visitorInvitation.findMany({ where: { sponsorMemberId: member.id }, include: invitationView, orderBy: { scheduledDate: 'desc' } })
    return { member: { id: member.id, fullName: user.person.fullName, cpf: user.person.cpf, birthDate: user.person.birthDate, phone: user.person.phone, email: user.person.email, city: user.person.city, photoPath: user.person.photoPath, credentialToken: user.person.credentialToken, category: member.category.name, registrationNumber: member.registrationNumber, status: member.status, admissionDate: member.admissionDate }, dependents: member.dependentes.map((d: any) => ({ id: d.id, fullName: d.person.fullName, cpf: d.person.cpf, birthDate: d.person.birthDate, photoPath: d.person.photoPath, credentialToken: d.person.credentialToken, relationship: d.relationship, active: d.status === 'ACTIVE' })), invitations, quota }
  })
  app.get('/member/me/invitations/quota', { preHandler: app.authenticate }, async (request: any, reply) => { const user = await memberFromAuth(request.authUser!.id); const member = user?.person?.member; if (!member) return reply.code(403).send({ message: 'Área disponível apenas para associados.' }); const requested = parseCivilDate(`${request.query?.year || new Date().getUTCFullYear()}-${String(request.query?.month || new Date().getUTCMonth() + 1).padStart(2, '0')}-01`) || new Date(); return { quota: await getMemberInvitationQuota(member.id, requested), invitations: await prisma.visitorInvitation.findMany({ where: { sponsorMemberId: member.id }, include: invitationView, orderBy: { scheduledDate: 'desc' } }) } })
  app.post('/member/me/visitors', { preHandler: app.authenticate }, async (request: any, reply) => { const b = request.body || {}; const cpf = normalizeCpf(b.cpf); if (!b.fullName?.trim() || !cpf) return reply.code(400).send({ message: 'Nome e CPF são obrigatórios.' }); const existing = await prisma.person.findUnique({ where: { cpf }, include: { visitor: true } }); if (existing) return existing.visitor || reply.code(409).send({ message: 'Já existe uma pessoa com este CPF.' }); const person = await prisma.person.create({ data: { fullName: b.fullName.trim(), cpf, phone: normalizePhone(b.phone), email: b.email?.trim().toLowerCase() || null, city: b.city?.trim() || null } }); return reply.code(201).send(await prisma.visitor.create({ data: { personId: person.id }, include: { person: true } })) })
  app.get('/member/me/visitors/search', { preHandler: app.authenticate }, async (request: any) => { const q = String(request.query?.q || '').trim(); if (q.length < 2) return []; const digits = q.replace(/\D/g, ''); return prisma.visitor.findMany({ where: { active: true, blocked: false, OR: [{ person: { fullName: { contains: q, mode: 'insensitive' } } }, ...(digits ? [{ person: { cpf: { contains: digits } } }, { person: { phone: { contains: digits } } }] : [])] }, include: { person: true }, orderBy: { person: { fullName: 'asc' } }, take: 20 }) })
  app.post('/member/me/invitations', { preHandler: app.authenticate }, async (request: any, reply) => { const user = await memberFromAuth(request.authUser!.id); const member = user?.person?.member; if (!member) return reply.code(403).send({ message: 'Área disponível apenas para associados.' }); try { return reply.code(201).send(await prisma.$transaction(tx => createInvitation({ ...request.body, sponsorMemberId: member.id }, tx))) } catch (e: any) { return reply.code(e.statusCode || 500).send({ message: e.message || 'Não foi possível criar o convite.' }) } })
  app.post('/member/me/invitations/:id/cancel', { preHandler: app.authenticate }, async (request: any, reply) => { const user = await memberFromAuth(request.authUser!.id); const member = user?.person?.member; const invitation = await prisma.visitorInvitation.findUnique({ where: { id: request.params.id } }); if (!member || !invitation || invitation.sponsorMemberId !== member.id) return reply.code(404).send({ message: 'Convite não encontrado.' }); if (invitation.status === 'USED') return reply.code(409).send({ message: 'Convite já utilizado não pode ser cancelado.' }); return prisma.visitorInvitation.update({ where: { id: invitation.id }, data: { status: 'CANCELLED' }, include: invitationView }) })
}
