// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { prisma } from '../../../lib/prisma.js'
import { hashPassword } from '../auth/password.js'
import { normalizeCpf, normalizePhone } from '../auth/normalization.js'

const statuses = ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED'] as const
const date = (value: unknown) => typeof value === 'string' && !Number.isNaN(Date.parse(value)) ? new Date(`${value}T00:00:00.000Z`) : null
const initialPassword = (value: Date) => { const d = value.toISOString().slice(0, 10).split('-'); return `${d[2]}${d[1]}${d[0]}` }
const maskCpf = (cpf: string) => `${cpf.slice(0, 3)}.${cpf.slice(3, 6)}.${cpf.slice(6, 9)}-${cpf.slice(9)}`
const include = { person: { include: { user: { select: { id: true, active: true } }, accessEvents: { where: { type: 'ENTRY' }, orderBy: { occurredAt: 'desc' }, take: 1 } } }, category: true, titular: { include: { person: true } }, dependentes: { include: { person: { include: { accessEvents: { where: { type: 'ENTRY' }, orderBy: { occurredAt: 'desc' }, take: 1 } } }, category: true } }, charges: { where: { status: { in: ['PENDING', 'OVERDUE'] } }, orderBy: { dueDate: 'asc' }, take: 1 } }
const view = (member: any) => ({ ...member, person: { ...member.person, cpf: maskCpf(member.person.cpf), birthDate: member.person.birthDate?.toISOString().slice(0, 10) ?? null }, admissionDate: member.admissionDate.toISOString().slice(0, 10), access: Boolean(member.person.user) ? 'ACTIVE' : 'NONE', dependents: (member.dependentes ?? []).map((dependent: any) => ({ ...dependent, status: dependent.status ?? 'ACTIVE', person: { ...dependent.person, cpf: maskCpf(dependent.person.cpf), birthDate: dependent.person.birthDate?.toISOString().slice(0, 10) ?? null } })) })
const validStatus = (status: string) => statuses.includes(status as any)

async function validateHierarchy(categoryId: string, titularMemberId: string | null, relationship: string | null, currentId?: string) {
  const category = await prisma.memberCategory.findUnique({ where: { id: categoryId } })
  if (!category) return 'Modalidade inválida.'
  const dependent = category.name === 'Dependente'
  if (dependent && !titularMemberId) return 'Dependente exige titular responsável.'
  if (dependent && !relationship?.trim()) return 'Dependente exige parentesco.'
  if (!dependent && titularMemberId) return 'Somente dependentes podem possuir titular responsável.'
  if (!titularMemberId) return null
  if (titularMemberId === currentId) return 'Um associado não pode ser titular de si mesmo.'
  const holder = await prisma.member.findUnique({ where: { id: titularMemberId }, include: { category: true } })
  if (!holder || holder.category.name === 'Dependente') return 'O titular selecionado deve ser um associado titular.'
  return null
}

async function saveMultipartPhoto(request: any, reply: any, dependent = false) {
  const member = await prisma.member.findUnique({ where: { id: request.params.id }, include: { dependentes: true } })
  if (!member) return reply.code(404).send({ message: 'Associado não encontrado.' })
  const personId = dependent ? member.dependentes.find((item: any) => item.id === request.params.dependentId)?.personId : member.personId
  if (!personId) return reply.code(404).send({ message: 'Dependente não encontrado.' })
  let part
  try { part = await request.file() } catch (error: any) { return reply.code(error?.code === 'FST_REQ_FILE_TOO_LARGE' ? 413 : 400).send({ message: error?.code === 'FST_REQ_FILE_TOO_LARGE' ? 'A foto deve ter no máximo 5 MB.' : 'Arquivo de foto inválido.' }) }
  if (!part) return reply.code(400).send({ message: 'Arquivo de foto obrigatório.' })
  const allowed: Record<string, string> = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' }
  const ext = allowed[part.mimetype]; if (!ext) return reply.code(400).send({ message: 'Formato inválido. Use JPG, JPEG, PNG ou WEBP.' })
  const buffer = await part.toBuffer(); if (buffer.length > 5 * 1024 * 1024) return reply.code(413).send({ message: 'A foto deve ter no máximo 5 MB.' })
  const directory = path.resolve(process.cwd(), 'uploads', 'person-photos'); await fs.mkdir(directory, { recursive: true }); const file = `${crypto.randomUUID()}.${ext}`; await fs.writeFile(path.join(directory, file), buffer)
  return prisma.person.update({ where: { id: personId }, data: { photoPath: `/uploads/person-photos/${file}` } })
}

export const memberRoutes: FastifyPluginAsync = async (app) => {
  app.post('/members/:id/photo', { preHandler: app.requirePermission('members.manage') }, saveMultipartPhoto)
  app.delete('/members/:id/photo', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const member = await prisma.member.findUnique({ where: { id: request.params.id } }); if (!member) return reply.code(404).send({ message: 'Associado não encontrado.' }); return prisma.person.update({ where: { id: member.personId }, data: { photoPath: null } }) })
  app.post('/members/:id/dependents/:dependentId/photo', { preHandler: app.requirePermission('members.manage') }, (request, reply) => saveMultipartPhoto(request, reply, true))
  app.delete('/members/:id/dependents/:dependentId/photo', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const dependent = await prisma.member.findFirst({ where: { id: request.params.dependentId, titularMemberId: request.params.id } }); if (!dependent) return reply.code(404).send({ message: 'Dependente não encontrado.' }); return prisma.person.update({ where: { id: dependent.personId }, data: { photoPath: null } }) })
  app.get('/uploads/person-photos/:file', async (request: any, reply) => { try { const file = path.basename(request.params.file); const data = await fs.readFile(path.resolve(process.cwd(), 'uploads', 'person-photos', file)); return reply.type(path.extname(file) === '.png' ? 'image/png' : path.extname(file) === '.webp' ? 'image/webp' : 'image/jpeg').send(data) } catch { return reply.code(404).send({ message: 'Imagem não encontrada.' }) } })
  app.get('/members/categories', { preHandler: app.requirePermission('members.view') }, async () => prisma.memberCategory.findMany({ where: { active: true }, orderBy: { name: 'asc' } }))
  app.get('/members', { preHandler: app.requirePermission('members.view') }, async (request: any) => { const q = request.query?.q?.trim(); const cpfDigits = q?.replace(/\D/g, ''); const rows = await prisma.member.findMany({ where: { ...(request.query?.categoryId ? { categoryId: request.query.categoryId } : {}), ...(validStatus(request.query?.status) ? { status: request.query.status } : {}), ...(q ? { OR: [{ person: { fullName: { contains: q, mode: 'insensitive' } } }, ...(cpfDigits ? [{ person: { cpf: { contains: cpfDigits } } }] : []), { registrationNumber: { contains: q, mode: 'insensitive' } }] } : {}) }, include, orderBy: { person: { fullName: 'asc' } } }); return rows.map(view) })
  app.get('/members/:id', { preHandler: app.requirePermission('members.view') }, async (request: any, reply) => { const member = await prisma.member.findUnique({ where: { id: request.params.id }, include }); if (!member) return reply.code(404).send({ message: 'Associado não encontrado.' }); return view(member) })
  app.get('/members/:id/dependents', { preHandler: app.requirePermission('members.view') }, async (request: any, reply) => { const member = await prisma.member.findUnique({ where: { id: request.params.id }, include }); if (!member) return reply.code(404).send({ message: 'Associado não encontrado.' }); return view(member).dependents })
  app.post('/members', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => {
    const body = request.body ?? {}; const cpf = normalizeCpf(body.cpf); const birthDate = date(body.birthDate); const admissionDate = date(body.admissionDate); const titularMemberId = body.titularMemberId || null; const relationship = body.relationship?.trim() || null
    if (!body.fullName?.trim() || !cpf || !birthDate || !body.categoryId || !admissionDate || !validStatus(body.status ?? 'ACTIVE')) return reply.code(400).send({ message: 'Nome, CPF, nascimento, modalidade e ingresso são obrigatórios.' })
    const hierarchyError = await validateHierarchy(body.categoryId, titularMemberId, relationship); if (hierarchyError) return reply.code(400).send({ message: hierarchyError })
    try { const person = await prisma.person.upsert({ where: { cpf }, update: { fullName: body.fullName.trim(), birthDate, phone: normalizePhone(body.phone), email: body.email?.trim().toLowerCase() || null, city: body.city?.trim() || null }, create: { fullName: body.fullName.trim(), cpf, birthDate, phone: normalizePhone(body.phone), email: body.email?.trim().toLowerCase() || null, city: body.city?.trim() || null } }); if (await prisma.member.findUnique({ where: { personId: person.id } })) return reply.code(409).send({ message: 'Este CPF já está cadastrado como associado.' }); const member = await prisma.member.create({ data: { personId: person.id, categoryId: body.categoryId, titularMemberId, relationship, registrationNumber: body.registrationNumber?.trim() || null, admissionDate, status: body.status ?? 'ACTIVE', notes: body.notes?.trim() || null } }); if (body.allowAccess && !(await prisma.user.findUnique({ where: { personId: person.id } }))) await prisma.user.create({ data: { personId: person.id, passwordHash: await hashPassword(initialPassword(birthDate)), mustChangePassword: true } }); return reply.code(201).send(view(await prisma.member.findUniqueOrThrow({ where: { id: member.id }, include }))) } catch (error: any) { if (error?.code === 'P2002') return reply.code(409).send({ message: 'CPF, email ou matrícula já cadastrado.' }); throw error }
  })
  app.put('/members/:id', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => {
    const body = request.body ?? {}; const current = await prisma.member.findUnique({ where: { id: request.params.id }, include: { person: true } }); if (!current) return reply.code(404).send({ message: 'Associado não encontrado.' }); const cpf = normalizeCpf(body.cpf); const birthDate = date(body.birthDate); const admissionDate = date(body.admissionDate); const titularMemberId = body.titularMemberId || null; const relationship = body.relationship?.trim() || null
    if (!body.fullName?.trim() || !cpf || !birthDate || !body.categoryId || !admissionDate || !validStatus(body.status)) return reply.code(400).send({ message: 'Dados do associado inválidos.' }); const hierarchyError = await validateHierarchy(body.categoryId, titularMemberId, relationship, current.id); if (hierarchyError) return reply.code(400).send({ message: hierarchyError })
    try { await prisma.person.update({ where: { id: current.personId }, data: { fullName: body.fullName.trim(), cpf, birthDate, phone: normalizePhone(body.phone), email: body.email?.trim().toLowerCase() || null, city: body.city?.trim() || null } }); await prisma.member.update({ where: { id: current.id }, data: { categoryId: body.categoryId, titularMemberId, relationship, registrationNumber: body.registrationNumber?.trim() || null, admissionDate, status: body.status, notes: body.notes?.trim() || null } }); if (body.allowAccess && !(await prisma.user.findUnique({ where: { personId: current.personId } }))) await prisma.user.create({ data: { personId: current.personId, passwordHash: await hashPassword(birthDate), mustChangePassword: true } }); return view(await prisma.member.findUniqueOrThrow({ where: { id: current.id }, include })) } catch (error: any) { if (error?.code === 'P2002') return reply.code(409).send({ message: 'CPF, email ou matrícula já cadastrado.' }); throw error }
  })
  app.post('/members/:id/dependents', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const holder = await prisma.member.findUnique({ where: { id: request.params.id }, include: { category: true } }); const dependentCategory = await prisma.memberCategory.findUnique({ where: { name: 'Dependente' } }); const body = request.body ?? {}; const cpf = normalizeCpf(body.cpf); const birthDate = date(body.birthDate); if (!holder || !dependentCategory) return reply.code(404).send({ message: 'Titular ou modalidade não encontrado.' }); if (!body.fullName?.trim() || !cpf || !birthDate || !body.relationship?.trim()) return reply.code(400).send({ message: 'Nome, CPF, nascimento e parentesco são obrigatórios.' }); try { const person = await prisma.person.upsert({ where: { cpf }, update: { fullName: body.fullName.trim(), birthDate, phone: normalizePhone(body.phone), city: body.city?.trim() || null }, create: { fullName: body.fullName.trim(), cpf, birthDate, phone: normalizePhone(body.phone), city: body.city?.trim() || null } }); const member = await prisma.member.create({ data: { personId: person.id, categoryId: dependentCategory.id, titularMemberId: holder.id, relationship: body.relationship.trim(), admissionDate: birthDate, status: body.active === false ? 'INACTIVE' : 'ACTIVE' }, include }); return reply.code(201).send(view(member)) } catch (error: any) { if (error?.code === 'P2002') return reply.code(409).send({ message: 'CPF já vinculado a um associado.' }); throw error } })
  app.put('/members/:id/dependents/:dependentId', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const dependent = await prisma.member.findFirst({ where: { id: request.params.dependentId, titularMemberId: request.params.id }, include: { category: true } }); const dependentCategory = await prisma.memberCategory.findUnique({ where: { name: 'Dependente' } }); if (!dependent || !dependentCategory) return reply.code(404).send({ message: 'Dependente não encontrado.' }); const body = request.body ?? {}; const cpf = normalizeCpf(body.cpf); const birthDate = date(body.birthDate); if (!body.fullName?.trim() || !cpf || !birthDate || !body.relationship?.trim()) return reply.code(400).send({ message: 'Nome, CPF, nascimento e parentesco são obrigatórios.' }); const person = await prisma.person.update({ where: { id: dependent.personId }, data: { fullName: body.fullName.trim(), cpf, birthDate, phone: normalizePhone(body.phone), city: body.city?.trim() || null } }); return view(await prisma.member.update({ where: { id: dependent.id }, data: { categoryId: dependentCategory.id, relationship: body.relationship.trim(), status: body.active === false ? 'INACTIVE' : 'ACTIVE' }, include })) })
  app.delete('/members/:id/dependents/:dependentId', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const dependent = await prisma.member.findFirst({ where: { id: request.params.dependentId, titularMemberId: request.params.id } }); if (!dependent) return reply.code(404).send({ message: 'Dependente não encontrado.' }); return prisma.member.update({ where: { id: dependent.id }, data: { status: 'INACTIVE' } }) })
}
