// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { promises as fs } from 'node:fs'
import crypto from 'node:crypto'
import { prisma } from '../../../lib/prisma.js'
import { hashPassword } from '../auth/password.js'
import { normalizeCpf, normalizePhone } from '../auth/normalization.js'
import { personPhotosDirectory, personPhotoPath } from '../../../config/storage.js'

const statuses = ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED']
const parseDate = (value: unknown) => typeof value === 'string' && !Number.isNaN(Date.parse(value)) ? new Date(`${value}T00:00:00.000Z`) : null
const initialPassword = (value: Date) => { const iso = value.toISOString().slice(0, 10).split('-'); return `${iso[2]}${iso[1]}${iso[0]}` }
const maskCpf = (cpf: string) => `${cpf.slice(0, 3)}.${cpf.slice(3, 6)}.${cpf.slice(6, 9)}-${cpf.slice(9)}`
const include = { person: { include: { user: { select: { id: true, active: true, lastLoginAt: true } }, accessEvents: { where: { type: 'ENTRY' }, orderBy: { occurredAt: 'desc' }, take: 1 } } }, category: true, titular: { include: { person: true, category: true } }, dependentes: { include: { person: { include: { accessEvents: { where: { type: 'ENTRY' }, orderBy: { occurredAt: 'desc' }, take: 1 } } }, category: true } }, charges: { where: { status: { in: ['PENDING', 'OVERDUE'] } }, orderBy: { dueDate: 'asc' }, take: 1 } }
const view = (member: any) => ({ ...member, person: { ...member.person, cpf: maskCpf(member.person.cpf), birthDate: member.person.birthDate?.toISOString().slice(0, 10) ?? null }, admissionDate: member.admissionDate.toISOString().slice(0, 10), access: member.person.user ? { active: member.person.user.active, lastLoginAt: member.person.user.lastLoginAt } : null, financialResponsible: member.category.isDependent || member.category.requiresHolder ? member.titular ? { id: member.titular.id, name: member.titular.person.fullName } : null : { id: member.id, name: member.person.fullName }, dependents: (member.dependentes ?? []).map((dependent: any) => ({ ...dependent, person: { ...dependent.person, cpf: maskCpf(dependent.person.cpf), birthDate: dependent.person.birthDate?.toISOString().slice(0, 10) ?? null } })) })

async function validateHierarchy(categoryId: string, holderId: string | null, relationship: string | null, currentId?: string) {
  const category = await prisma.memberCategory.findUnique({ where: { id: categoryId } })
  if (!category) return 'Modalidade inválida.'
  const dependent = category.isDependent || category.requiresHolder
  if (dependent && !holderId) return 'Esta modalidade exige titular responsável.'
  if (dependent && !relationship?.trim()) return 'Esta modalidade exige parentesco.'
  if (!dependent && holderId) return 'Somente modalidades dependentes podem possuir titular.'
  if (!holderId) return null
  if (holderId === currentId) return 'Um associado não pode ser titular de si mesmo.'
  const holder = await prisma.member.findUnique({ where: { id: holderId }, include: { category: true } })
  if (!holder || holder.category.isDependent || holder.category.requiresHolder) return 'O titular selecionado deve ser um associado titular.'
  return null
}
async function ensureMemberUser(personId: string, birthDate: Date) { const user = await prisma.user.upsert({ where: { personId }, update: {}, create: { personId, passwordHash: await hashPassword(initialPassword(birthDate)), mustChangePassword: true } }); const role = await prisma.role.findUnique({ where: { name: 'SOCIO' } }); if (role) await prisma.userRole.upsert({ where: { userId_roleId: { userId: user.id, roleId: role.id } }, update: {}, create: { userId: user.id, roleId: role.id } }); return user }
async function uploadPhoto(request: any, reply: any) { const member = await prisma.member.findUnique({ where: { id: request.params.id } }); if (!member) return reply.code(404).send({ message: 'Associado não encontrado.' }); const part = await request.file().catch(() => null); if (!part) return reply.code(400).send({ message: 'Arquivo de foto obrigatório.' }); const extension = ({ 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' } as any)[part.mimetype]; if (!extension) return reply.code(400).send({ message: 'Formato inválido. Use JPG, PNG ou WEBP.' }); const buffer = await part.toBuffer(); if (buffer.length > 5 * 1024 * 1024) return reply.code(413).send({ message: 'A foto deve ter no máximo 5 MB.' }); await fs.mkdir(personPhotosDirectory, { recursive: true }); const file = `${crypto.randomUUID()}.${extension}`; await fs.writeFile(personPhotoPath(file), buffer); await prisma.person.update({ where: { id: member.personId }, data: { photoPath: `/uploads/person-photos/${file}` } }); return view(await prisma.member.findUniqueOrThrow({ where: { id: member.id }, include })) }

export const memberRoutes: FastifyPluginAsync = async (app) => {
  app.get('/members/categories', { preHandler: app.requirePermission('members.view') }, async () => prisma.memberCategory.findMany({ where: { active: true }, orderBy: { name: 'asc' } }))
  app.get('/member-categories', { preHandler: app.requirePermission('members.view') }, async () => prisma.memberCategory.findMany({ orderBy: { name: 'asc' } }))
  app.post('/member-categories', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const b = request.body ?? {}; if (!b.name?.trim()) return reply.code(400).send({ message: 'Nome da modalidade é obrigatório.' }); try { return reply.code(201).send(await prisma.memberCategory.create({ data: { name: b.name.trim(), description: b.description?.trim() || null, active: b.active !== false, isDependent: Boolean(b.isDependent), requiresHolder: Boolean(b.requiresHolder ?? b.isDependent), annualFeeAmount: b.annualFeeAmount ?? null } })) } catch (e: any) { if (e.code === 'P2002') return reply.code(409).send({ message: 'Modalidade já cadastrada.' }); throw e } })
  app.put('/member-categories/:id', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { try { return await prisma.memberCategory.update({ where: { id: request.params.id }, data: { name: request.body?.name?.trim(), description: request.body?.description?.trim() || null, active: request.body?.active !== false, isDependent: Boolean(request.body?.isDependent), requiresHolder: Boolean(request.body?.requiresHolder ?? request.body?.isDependent), annualFeeAmount: request.body?.annualFeeAmount ?? null } }) } catch { return reply.code(404).send({ message: 'Modalidade não encontrada.' }) } })
  app.delete('/member-categories/:id', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const count = await prisma.member.count({ where: { categoryId: request.params.id } }); if (count) return reply.code(409).send({ message: 'Modalidade utilizada por associados; desative-a em vez de excluir.' }); try { await prisma.memberCategory.delete({ where: { id: request.params.id } }); return { ok: true } } catch { return reply.code(404).send({ message: 'Modalidade não encontrada.' }) } })
  app.get('/members/holders/search', { preHandler: app.requirePermission('members.view') }, async (request: any) => { const q = String(request.query?.q ?? '').trim(); if (q.length < 2) return []; const cpf = q.replace(/\D/g, ''); const rows = await prisma.member.findMany({ where: { status: 'ACTIVE', category: { isDependent: false, requiresHolder: false }, OR: [{ person: { fullName: { contains: q, mode: 'insensitive' } } }, ...(cpf ? [{ person: { cpf: { contains: cpf } } }] : [])] }, include: { person: true }, orderBy: { person: { fullName: 'asc' } }, take: 8 }); return rows.map((m: any) => ({ id: m.id, name: m.person.fullName, cpf: maskCpf(m.person.cpf) })) })
  app.post('/members/:id/photo', { preHandler: app.requirePermission('members.manage') }, uploadPhoto)
  app.delete('/members/:id/photo', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const member = await prisma.member.findUnique({ where: { id: request.params.id } }); if (!member) return reply.code(404).send({ message: 'Associado não encontrado.' }); return prisma.person.update({ where: { id: member.personId }, data: { photoPath: null } }) })
  app.get('/members', { preHandler: app.requirePermission('members.view') }, async (request: any) => { const q = request.query?.q?.trim(); const cpf = q?.replace(/\D/g, ''); const rows = await prisma.member.findMany({ where: { ...(request.query?.categoryId ? { categoryId: request.query.categoryId } : {}), ...(statuses.includes(request.query?.status) ? { status: request.query.status } : {}), ...(q ? { OR: [{ person: { fullName: { contains: q, mode: 'insensitive' } } }, ...(cpf ? [{ person: { cpf: { contains: cpf } } }] : []), { registrationNumber: { contains: q, mode: 'insensitive' } }] } : {}) }, include, orderBy: { person: { fullName: 'asc' } } }); return rows.map(view) })
  app.get('/members/:id', { preHandler: app.requirePermission('members.view') }, async (request: any, reply) => { const row = await prisma.member.findUnique({ where: { id: request.params.id }, include }); if (!row) return reply.code(404).send({ message: 'Associado não encontrado.' }); return view(row) })
  app.post('/members', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const b = request.body ?? {}; const cpf = normalizeCpf(b.cpf); const birthDate = parseDate(b.birthDate); const admissionDate = parseDate(b.admissionDate); const holder = b.titularMemberId || null; const error = await validateHierarchy(b.categoryId, holder, b.relationship); if (!b.fullName?.trim() || !cpf || !birthDate || !admissionDate || !b.categoryId || error) return reply.code(400).send({ message: error || 'Nome, CPF, nascimento, modalidade e ingresso são obrigatórios.' }); try { const person = await prisma.person.create({ data: { fullName: b.fullName.trim(), cpf, birthDate, phone: normalizePhone(b.phone), email: b.email?.trim().toLowerCase() || null, city: b.city?.trim() || null } }); const member = await prisma.member.create({ data: { personId: person.id, categoryId: b.categoryId, titularMemberId: holder, relationship: b.relationship?.trim() || null, registrationNumber: b.registrationNumber?.trim() || null, admissionDate, status: b.status || 'ACTIVE', notes: b.notes?.trim() || null } }); await ensureMemberUser(person.id, birthDate); return reply.code(201).send(view(await prisma.member.findUniqueOrThrow({ where: { id: member.id }, include }))) } catch (e: any) { if (e.code === 'P2002') return reply.code(409).send({ message: 'CPF, email ou matrícula já cadastrado.' }); throw e } })
  app.put('/members/:id', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const b = request.body ?? {}; const current = await prisma.member.findUnique({ where: { id: request.params.id }, include: { person: true } }); if (!current) return reply.code(404).send({ message: 'Associado não encontrado.' }); const cpf = normalizeCpf(b.cpf); const birthDate = parseDate(b.birthDate); const admissionDate = parseDate(b.admissionDate); const holder = b.titularMemberId || null; const error = await validateHierarchy(b.categoryId, holder, b.relationship, current.id); if (!birthDate || !admissionDate || !cpf || error) return reply.code(400).send({ message: error || 'Dados inválidos.' }); try { await prisma.person.update({ where: { id: current.personId }, data: { fullName: b.fullName.trim(), cpf, birthDate, phone: normalizePhone(b.phone), email: b.email?.trim().toLowerCase() || null, city: b.city?.trim() || null } }); await prisma.member.update({ where: { id: current.id }, data: { categoryId: b.categoryId, titularMemberId: holder, relationship: b.relationship?.trim() || null, registrationNumber: b.registrationNumber?.trim() || null, admissionDate, status: b.status, notes: b.notes?.trim() || null } }); await ensureMemberUser(current.personId, birthDate); return view(await prisma.member.findUniqueOrThrow({ where: { id: current.id }, include })) } catch (e: any) { if (e.code === 'P2002') return reply.code(409).send({ message: 'CPF, email ou matrícula já cadastrado.' }); throw e } })
  app.post('/members/:id/access/toggle', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const member = await prisma.member.findUnique({ where: { id: request.params.id }, include: { person: true } }); if (!member) return reply.code(404).send({ message: 'Associado não encontrado.' }); const user = await ensureMemberUser(member.personId, member.person.birthDate!); return prisma.user.update({ where: { id: user.id }, data: { active: request.body?.active !== false } }) })
  app.post('/members/:id/access/reset-password', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const member = await prisma.member.findUnique({ where: { id: request.params.id }, include: { person: true } }); if (!member?.person.birthDate) return reply.code(404).send({ message: 'Associado ou nascimento não encontrado.' }); const user = await ensureMemberUser(member.personId, member.person.birthDate); await prisma.user.update({ where: { id: user.id }, data: { passwordHash: await hashPassword(initialPassword(member.person.birthDate)), mustChangePassword: true, active: true } }); return { ok: true, message: 'Senha redefinida para a data de nascimento.' } })
  app.get('/members/:id/dependents', { preHandler: app.requirePermission('members.view') }, async (request: any, reply) => { const row = await prisma.member.findUnique({ where: { id: request.params.id }, include }); if (!row) return reply.code(404).send({ message: 'Associado não encontrado.' }); return view(row).dependents })
  app.post('/members/:id/dependents', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const holder = await prisma.member.findUnique({ where: { id: request.params.id } }); const category = await prisma.memberCategory.findFirst({ where: { isDependent: true } }); const b = request.body ?? {}; if (!holder || !category) return reply.code(404).send({ message: 'Titular ou modalidade dependente não encontrado.' }); const birthDate = parseDate(b.birthDate); if (!b.fullName || !birthDate || !b.cpf || !b.relationship) return reply.code(400).send({ message: 'Nome, CPF, nascimento e parentesco são obrigatórios.' }); const person = await prisma.person.create({ data: { fullName: b.fullName.trim(), cpf: normalizeCpf(b.cpf), birthDate, phone: normalizePhone(b.phone), city: b.city || null } }); const member = await prisma.member.create({ data: { personId: person.id, categoryId: category.id, titularMemberId: holder.id, relationship: b.relationship.trim(), admissionDate: birthDate, status: b.active === false ? 'INACTIVE' : 'ACTIVE' } }); await ensureMemberUser(person.id, birthDate); return reply.code(201).send(view(await prisma.member.findUniqueOrThrow({ where: { id: member.id }, include }))) })
  app.put('/members/:id/dependents/:dependentId', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const member = await prisma.member.findFirst({ where: { id: request.params.dependentId, titularMemberId: request.params.id }, include: { person: true } }); if (!member) return reply.code(404).send({ message: 'Dependente não encontrado.' }); const b = request.body ?? {}; const birthDate = parseDate(b.birthDate); if (!birthDate) return reply.code(400).send({ message: 'Nascimento inválido.' }); await prisma.person.update({ where: { id: member.personId }, data: { fullName: b.fullName, cpf: normalizeCpf(b.cpf), birthDate, phone: normalizePhone(b.phone), city: b.city || null } }); return view(await prisma.member.update({ where: { id: member.id }, data: { relationship: b.relationship, status: b.active === false ? 'INACTIVE' : 'ACTIVE' }, include })) })
  app.delete('/members/:id/dependents/:dependentId', { preHandler: app.requirePermission('members.manage') }, async (request: any, reply) => { const member = await prisma.member.findFirst({ where: { id: request.params.dependentId, titularMemberId: request.params.id } }); if (!member) return reply.code(404).send({ message: 'Dependente não encontrado.' }); return prisma.member.update({ where: { id: member.id }, data: { status: 'INACTIVE' } }) })
}
