// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
const include={space:true,member:{include:{person:true}}}
const dateOnly=(v:any)=>{const d=new Date(`${v}T00:00:00Z`);return Number.isNaN(d.getTime())?null:d}
export const reservationRoutes:FastifyPluginAsync=async app=>{
 app.get('/reservable-spaces',{preHandler:app.authenticate},async()=>prisma.reservableSpace.findMany({where:{active:true},orderBy:{name:'asc'}}))
 app.get('/member/me/reservations',{preHandler:app.authenticate},async req=>{const u=await prisma.user.findUnique({where:{id:req.authUser!.id},include:{person:{include:{member:true}}}});if(!u?.person.member)return [];return prisma.reservation.findMany({where:{memberId:u.person.member.id},include:{space:true},orderBy:{reservationDate:'desc'}})})
 app.post('/member/me/reservations',{preHandler:app.authenticate},async(req:any,reply)=>{const u=await prisma.user.findUnique({where:{id:req.authUser!.id},include:{person:{include:{member:true}}}});const b=req.body??{},d=dateOnly(b.reservationDate),s=u?.person.member&&await prisma.reservableSpace.findUnique({where:{id:b.spaceId}});if(!u?.person.member||u.person.member.status!=='ACTIVE')return reply.code(403).send({message:'Apenas associados ativos podem solicitar reservas.'});if(!s||!s.active||!d)return reply.code(400).send({message:'Espaço ou data inválidos.'});const conflict=await prisma.reservation.findFirst({where:{spaceId:s.id,reservationDate:d,status:'APPROVED',...(b.startTime&&b.endTime?{OR:[{startTime:null},{startTime:{lt:b.endTime},endTime:{gt:b.startTime}}]}:{})}});if(conflict)return reply.code(409).send({message:'Este espaço já possui uma reserva aprovada para a data selecionada.'});return reply.code(201).send(await prisma.reservation.create({data:{memberId:u.person.member.id,spaceId:s.id,reservationDate:d,startTime:b.startTime||null,endTime:b.endTime||null,totalAmount:s.price,notes:b.notes||null},include:{space:true}}))})
 app.post('/member/me/reservations/:id/cancel',{preHandler:app.authenticate},async(req:any,reply)=>{const u=await prisma.user.findUnique({where:{id:req.authUser!.id},include:{person:{include:{member:true}}}});const r=await prisma.reservation.findFirst({where:{id:req.params.id,memberId:u?.person.member?.id}});if(!r)return reply.code(404).send({message:'Reserva não encontrada.'});if(['COMPLETED','CANCELLED'].includes(r.status))return reply.code(400).send({message:'Esta reserva não pode ser cancelada.'});return prisma.reservation.update({where:{id:r.id},data:{status:'CANCELLED'}})})
 app.get('/reservations',{preHandler:app.requirePermission('reservations.view')},async(req:any)=>prisma.reservation.findMany({where:{...(req.query?.status?{status:req.query.status}:{}),...(req.query?.spaceId?{spaceId:req.query.spaceId}:{})},include,orderBy:{reservationDate:'desc'}}))
 app.post('/reservations/:id/approve',{preHandler:app.requirePermission('reservations.manage')},async(req:any,reply)=>{const r=await prisma.reservation.findUnique({where:{id:req.params.id}});if(!r)return reply.code(404).send({message:'Reserva não encontrada.'});const conflict=await prisma.reservation.findFirst({where:{id:{not:r.id},spaceId:r.spaceId,reservationDate:r.reservationDate,status:'APPROVED'}});if(conflict)return reply.code(409).send({message:'Conflito com outra reserva aprovada.'});return prisma.reservation.update({where:{id:r.id},data:{status:'APPROVED',approvedAt:new Date(),approvedByUserId:req.authUser!.id},include})})
 app.post('/reservations/:id/reject',{preHandler:app.requirePermission('reservations.manage')},async(req:any,reply)=>{const r=await prisma.reservation.findUnique({where:{id:req.params.id}});if(!r)return reply.code(404).send({message:'Reserva não encontrada.'});return prisma.reservation.update({where:{id:r.id},data:{status:'REJECTED',rejectionReason:req.body?.reason||'Não informado'},include})})
}
