// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
const include = { space: true, member: { include: { person: true } } }
const dateOnly = (v: any) => { const d = new Date(`${v}T00:00:00Z`); return Number.isNaN(d.getTime()) ? null : d }
const overlaps = (a: any, b: any) => !a || !b || (!a.startTime || !a.endTime || !b.startTime || !b.endTime || (a.startTime < b.endTime && a.endTime > b.startTime))
const validTimes = (start: any, end: any) => (!start && !end) || (typeof start === 'string' && typeof end === 'string' && /^\d{2}:\d{2}$/.test(start) && /^\d{2}:\d{2}$/.test(end) && start < end)
async function conflict(spaceId: string, date: Date, startTime: string | null, endTime: string | null, exceptId?: string) { const rows = await prisma.reservation.findMany({ where: { spaceId, reservationDate: date, status: { in: ['REQUESTED', 'APPROVED'] }, ...(exceptId ? { id: { not: exceptId } } : {}) } }); return rows.find((row) => overlaps({ startTime, endTime }, row)) }
export const reservationRoutes: FastifyPluginAsync = async (app) => {
  app.get('/reservable-spaces', { preHandler: app.authenticate }, async () => prisma.reservableSpace.findMany({ where: { active: true }, orderBy: { name: 'asc' } }))
  app.get('/spaces', { preHandler: app.requirePermission('reservations.view') }, async () => prisma.reservableSpace.findMany({ orderBy: { name: 'asc' } }))
  app.post('/spaces', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { const b = request.body ?? {}; const capacity = b.capacity == null || b.capacity === '' ? null : Number(b.capacity); const price = Number(b.price); if (!b.name?.trim() || b.price == null || !Number.isFinite(price) || price < 0 || (capacity != null && (!Number.isInteger(capacity) || capacity < 1))) return reply.code(400).send({ message: 'Nome, valor e capacidade válida devem ser informados.' }); try { return reply.code(201).send(await prisma.reservableSpace.create({ data: { name: b.name.trim(), description: b.description?.trim() || null, capacity, price, active: b.active !== false, imagePath: b.imagePath?.trim() || null, requiresApproval: b.requiresApproval !== false, reservationRules: b.reservationRules?.trim() || null } })) } catch (e: any) { if (e.code === 'P2002') return reply.code(409).send({ message: 'Já existe um espaço com este nome.' }); throw e } })
  app.get('/spaces/:id', { preHandler: app.requirePermission('reservations.view') }, async (request: any, reply) => { const row = await prisma.reservableSpace.findUnique({ where: { id: request.params.id } }); return row ? row : reply.code(404).send({ message: 'Espaço não encontrado.' }) })
  app.put('/spaces/:id', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { const b = request.body ?? {}; const capacity = b.capacity == null || b.capacity === '' ? null : Number(b.capacity); const price = Number(b.price); if (!b.name?.trim() || b.price == null || !Number.isFinite(price) || price < 0 || (capacity != null && (!Number.isInteger(capacity) || capacity < 1))) return reply.code(400).send({ message: 'Nome, valor e capacidade válida devem ser informados.' }); try { return await prisma.reservableSpace.update({ where: { id: request.params.id }, data: { name: b.name.trim(), description: b.description?.trim() || null, capacity, price, active: b.active !== false, imagePath: b.imagePath?.trim() || null, requiresApproval: b.requiresApproval !== false, reservationRules: b.reservationRules?.trim() || null } }) } catch (e: any) { if (e.code === 'P2002') return reply.code(409).send({ message: 'Já existe um espaço com este nome.' }); return reply.code(404).send({ message: 'Espaço não encontrado.' }) } })
  app.delete('/spaces/:id', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { const count = await prisma.reservation.count({ where: { spaceId: request.params.id } }); if (count) return reply.code(409).send({ message: 'Espaço possui histórico; desative-o em vez de excluir.' }); try { await prisma.reservableSpace.delete({ where: { id: request.params.id } }); return { ok: true } } catch { return reply.code(404).send({ message: 'Espaço não encontrado.' }) } })
  app.get('/member/me/reservations', { preHandler: app.authenticate }, async (request: any) => { const u = await prisma.user.findUnique({ where: { id: request.authUser.id }, include: { person: { include: { member: true } } } }); if (!u?.person.member) return []; return prisma.reservation.findMany({ where: { memberId: u.person.member.id }, include: { space: true }, orderBy: { reservationDate: 'desc' } }) })
  app.post('/member/me/reservations', { preHandler: app.authenticate }, async (request: any, reply) => { const u = await prisma.user.findUnique({ where: { id: request.authUser.id }, include: { person: { include: { member: true } } } }); const b = request.body ?? {}; const d = dateOnly(b.reservationDate); const space = await prisma.reservableSpace.findUnique({ where: { id: b.spaceId } }); if (!u?.person.member || u.person.member.status !== 'ACTIVE') return reply.code(403).send({ message: 'Apenas associados ativos podem solicitar reservas.' }); if (!space?.active || !d || !validTimes(b.startTime, b.endTime)) return reply.code(400).send({ message: 'Espaço, data e horário devem ser válidos.' }); if (await conflict(space.id, d, b.startTime || null, b.endTime || null)) return reply.code(409).send({ message: 'Conflito de horário para este espaço.' }); return reply.code(201).send(await prisma.reservation.create({ data: { memberId: u.person.member.id, spaceId: space.id, reservationDate: d, startTime: b.startTime || null, endTime: b.endTime || null, totalAmount: space.price, notes: b.notes || null }, include })) })
  app.post('/member/me/reservations/:id/cancel', { preHandler: app.authenticate }, async (request: any, reply) => { const u = await prisma.user.findUnique({ where: { id: request.authUser.id }, include: { person: { include: { member: true } } } }); const row = await prisma.reservation.findFirst({ where: { id: request.params.id, memberId: u?.person.member?.id } }); if (!row) return reply.code(404).send({ message: 'Reserva não encontrada.' }); if (['COMPLETED', 'CANCELLED'].includes(row.status)) return reply.code(400).send({ message: 'Esta reserva não pode ser cancelada.' }); return prisma.reservation.update({ where: { id: row.id }, data: { status: 'CANCELLED' }, include }) })
  app.get('/reservations', { preHandler: app.requirePermission('reservations.view') }, async (request: any) => prisma.reservation.findMany({ where: { ...(request.query?.status ? { status: request.query.status } : {}), ...(request.query?.spaceId ? { spaceId: request.query.spaceId } : {}), ...(request.query?.from || request.query?.to ? { reservationDate: { ...(request.query.from ? { gte: dateOnly(request.query.from) } : {}), ...(request.query.to ? { lte: dateOnly(request.query.to) } : {}) } } : {}) }, include, orderBy: { reservationDate: 'desc' } }))
  app.post('/reservations', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { const b = request.body ?? {}; const d = dateOnly(b.reservationDate); const space = await prisma.reservableSpace.findUnique({ where: { id: b.spaceId } }); if (!space || !d || !b.memberId || !validTimes(b.startTime, b.endTime)) return reply.code(400).send({ message: 'Associado, espaço, data e horário devem ser válidos.' }); if (await conflict(space.id, d, b.startTime || null, b.endTime || null)) return reply.code(409).send({ message: 'Conflito de horário para este espaço.' }); return reply.code(201).send(await prisma.reservation.create({ data: { memberId: b.memberId, spaceId: space.id, reservationDate: d, startTime: b.startTime || null, endTime: b.endTime || null, totalAmount: b.totalAmount ?? space.price, status: b.status || 'APPROVED', approvedAt: b.status === 'APPROVED' ? new Date() : null, approvedByUserId: b.status === 'APPROVED' ? request.authUser.id : null, notes: b.notes || null }, include })) })
  app.put('/reservations/:id', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { const b = request.body ?? {}; const current = await prisma.reservation.findUnique({ where: { id: request.params.id } }); if (!current) return reply.code(404).send({ message: 'Reserva não encontrada.' }); const d = dateOnly(b.reservationDate); const space = await prisma.reservableSpace.findUnique({ where: { id: b.spaceId } }); if (!space || !d || !b.memberId || !validTimes(b.startTime, b.endTime)) return reply.code(400).send({ message: 'Associado, espaço, data e horário devem ser válidos.' }); if (await conflict(space.id, d, b.startTime || null, b.endTime || null, current.id)) return reply.code(409).send({ message: 'Conflito de horário para este espaço.' }); return prisma.reservation.update({ where: { id: current.id }, data: { memberId: b.memberId, spaceId: space.id, reservationDate: d, startTime: b.startTime || null, endTime: b.endTime || null, totalAmount: b.totalAmount ?? space.price, notes: b.notes?.trim() || null }, include }) })
  app.post('/reservations/:id/approve', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { const row = await prisma.reservation.findUnique({ where: { id: request.params.id } }); if (!row) return reply.code(404).send({ message: 'Reserva não encontrada.' }); if (await conflict(row.spaceId, row.reservationDate, row.startTime, row.endTime, row.id)) return reply.code(409).send({ message: 'Conflito com outra reserva.' }); return prisma.reservation.update({ where: { id: row.id }, data: { status: 'APPROVED', approvedAt: new Date(), approvedByUserId: request.authUser.id }, include }) })
  app.post('/reservations/:id/reject', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { try { return await prisma.reservation.update({ where: { id: request.params.id }, data: { status: 'REJECTED', rejectionReason: request.body?.reason || 'Não informado' }, include }) } catch { return reply.code(404).send({ message: 'Reserva não encontrada.' }) } })
  app.post('/reservations/:id/cancel', { preHandler: app.requirePermission('reservations.manage') }, async (request: any, reply) => { try { return await prisma.reservation.update({ where: { id: request.params.id }, data: { status: 'CANCELLED' }, include }) } catch { return reply.code(404).send({ message: 'Reserva não encontrada.' }) } })
}
