// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
import { normalizeCpf, normalizePhone } from '../auth/normalization.js'
const mask=(v:string)=>`${v.slice(0,3)}.${v.slice(3,6)}.${v.slice(6,9)}-${v.slice(9)}`
const day=(v:any)=>new Date(`${v}T00:00:00.000Z`)
const visitorInclude={person:true,invitations:{include:{sponsorMember:{include:{person:true}}},orderBy:{scheduledDate:'desc'}}}
export const visitorRoutes:FastifyPluginAsync=async app=>{
 app.get('/visitors',{preHandler:app.requirePermission('visitors.view')},async(req:any)=>{const q=req.query?.q?.trim();const rows=await prisma.visitor.findMany({where:q?{OR:[{person:{fullName:{contains:q,mode:'insensitive'}}},{person:{cpf:{contains:q.replace(/\D/g,'')}}},{person:{phone:{contains:q.replace(/\D/g,'')}}}]}:{},include:visitorInclude,orderBy:{person:{fullName:'asc'}}});return rows.map((v:any)=>({...v,person:{...v.person,cpf:mask(v.person.cpf)},visitsThisYear:v.invitations.filter((i:any)=>i.status==='USED'&&i.usedAt&&new Date(i.usedAt).getFullYear()===new Date().getFullYear()).length}))})
 app.get('/visitors/:id',{preHandler:app.requirePermission('visitors.view')},async(req:any,reply)=>{const v=await prisma.visitor.findUnique({where:{id:req.params.id},include:visitorInclude});if(!v)return reply.code(404).send({message:'Visitante não encontrado.'});return {...v,person:{...v.person,cpf:mask(v.person.cpf)}}})
 app.post('/visitors',{preHandler:app.requirePermission('visitors.manage')},async(req:any,reply)=>{const b=req.body??{},cpf=normalizeCpf(b.cpf);if(!b.fullName?.trim()||!cpf||!b.phone?.trim()||!b.city?.trim())return reply.code(400).send({message:'Nome, CPF, telefone e cidade são obrigatórios.'});try{const person=await prisma.person.upsert({where:{cpf},update:{fullName:b.fullName.trim(),phone:normalizePhone(b.phone),city:b.city.trim(),email:b.email?.trim().toLowerCase()||null,birthDate:b.birthDate?day(b.birthDate):null},create:{fullName:b.fullName.trim(),cpf,phone:normalizePhone(b.phone),city:b.city.trim(),email:b.email?.trim().toLowerCase()||null,birthDate:b.birthDate?day(b.birthDate):null}});if(await prisma.visitor.findUnique({where:{personId:person.id}}))return reply.code(409).send({message:'Este CPF já está cadastrado como visitante.'});return reply.code(201).send(await prisma.visitor.create({data:{personId:person.id,notes:b.notes?.trim()||null},include:{person:true}}))}catch(e:any){if(e.code==='P2002')return reply.code(409).send({message:'CPF ou email já cadastrado.'});throw e}})
 app.put('/visitors/:id',{preHandler:app.requirePermission('visitors.manage')},async(req:any,reply)=>{const v=await prisma.visitor.findUnique({where:{id:req.params.id}});const b=req.body??{},cpf=normalizeCpf(b.cpf);if(!v)return reply.code(404).send({message:'Visitante não encontrado.'});if(!b.fullName?.trim()||!cpf||!b.phone?.trim()||!b.city?.trim())return reply.code(400).send({message:'Dados inválidos.'});const p=await prisma.person.update({where:{id:v.personId},data:{fullName:b.fullName.trim(),cpf,phone:normalizePhone(b.phone),city:b.city.trim(),email:b.email?.trim().toLowerCase()||null,birthDate:b.birthDate?day(b.birthDate):null}});return prisma.visitor.update({where:{id:v.id},data:{notes:b.notes?.trim()||null},include:{person:p}})})
 app.post('/visitors/:id/block',{preHandler:app.requirePermission('visitors.manage')},async(req:any,reply)=>{const v=await prisma.visitor.findUnique({where:{id:req.params.id}});if(!v)return reply.code(404).send({message:'Visitante não encontrado.'});return prisma.visitor.update({where:{id:v.id},data:{blocked:!v.blocked}})})
 app.get('/invitations',{preHandler:app.requirePermission('visitors.view')},async()=>prisma.visitorInvitation.findMany({include:{visitor:{include:{person:true}},sponsorMember:{include:{person:true}}},orderBy:{scheduledDate:'desc'}}))
 app.post('/invitations',{preHandler:app.requirePermission('visitors.manage')},async(req:any,reply)=>{const b=req.body??{},s=await prisma.member.findUnique({where:{id:b.sponsorMemberId},include:{person:true}}),v=await prisma.visitor.findUnique({where:{id:b.visitorId}});if(!s||s.status!=='ACTIVE')return reply.code(400).send({message:'O sócio responsável precisa estar ativo.'});if(!v||v.blocked||!v.active)return reply.code(400).send({message:'Visitante bloqueado ou inativo.'});return reply.code(201).send(await prisma.visitorInvitation.create({data:{visitorId:v.id,sponsorMemberId:s.id,scheduledDate:day(b.scheduledDate),notes:b.notes?.trim()||null},include:{visitor:{include:{person:true}},sponsorMember:{include:{person:true}}}}))})
 app.post('/invitations/:id/cancel',{preHandler:app.requirePermission('visitors.manage')},async(req:any,reply)=>{const i=await prisma.visitorInvitation.findUnique({where:{id:req.params.id}});if(!i)return reply.code(404).send({message:'Convite não encontrado.'});return prisma.visitorInvitation.update({where:{id:i.id},data:{status:'CANCELLED'}})})
}
