// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'

const point = () => prisma.accessPoint.findFirstOrThrow({ where: { active: true } })
const memberInclude = { category: true, titular: { include: { person: true } } }

export const accessRoutes: FastifyPluginAsync = async (app) => {
  app.post('/access/validate-credential', { preHandler: app.requirePermission('access.view') }, async (request: any, reply) => {
    const person = await prisma.person.findUnique({ where: { credentialToken: request.body?.credentialToken }, include: { member: { include: memberInclude } } })
    if (!person) return reply.code(404).send({ message: 'Credencial não encontrada.' })
    const member = person.member
    if (!member) return reply.code(403).send({ message: 'Pessoa não autorizada.' })
    const dependent = member.category.name === 'Dependente'
    const subject = { type: dependent ? 'Dependente' : 'Sócio', status: member.status, category: member.category.name, holderName: dependent ? member.titular?.person.fullName : undefined, memberId: member.id }
    return { person: { id: person.id, fullName: person.fullName, photoPath: person.photoPath, cpf: `${person.cpf.slice(0, 3)}.***.***-**` }, subject, allowed: subject.status === 'ACTIVE' }
  })
  app.get('/access/visitor/:cpf', { preHandler: app.requirePermission('access.view') }, async (request: any, reply) => {
    const cpf = String(request.params.cpf).replace(/\D/g, ''); const visitor = await prisma.visitor.findFirst({ where: { person: { cpf } }, include: { person: true, invitations: { include: { sponsorMember: { include: { person: true } } } } } }); if (!visitor) return reply.code(404).send({ message: 'Visitante não cadastrado.' })
    const now = new Date(); const year = now.getUTCFullYear(); const month = now.getUTCMonth(); const used = visitor.invitations.filter((item: any) => item.status === 'USED' && item.usedAt && new Date(item.usedAt).getUTCFullYear() === year).length; const settings = await prisma.clubSetting.findFirstOrThrow(); const valid = visitor.invitations.filter((item: any) => item.status === 'SCHEDULED' && new Date(item.scheduledDate).toDateString() === now.toDateString()); const sponsor = valid[0]?.sponsorMember; const monthly = sponsor ? await prisma.accessEvent.count({ where: { invitation: { sponsorMemberId: sponsor.id }, type: 'ENTRY', occurredAt: { gte: new Date(Date.UTC(year, month, 1)) } } }) : 0
    return { visitor: { id: visitor.id, person: { fullName: visitor.person.fullName, cpf: `${cpf.slice(0, 3)}.***.***-**`, phone: visitor.person.phone, city: visitor.person.city }, blocked: visitor.blocked, active: visitor.active }, invitations: valid, visitsUsed: used, annualLimit: settings.visitorAnnualLimit, monthlyUsed: monthly, monthlyLimit: settings.memberMonthlyInvitationLimit, sponsor: sponsor?.person.fullName, authorized: !!valid.length && !visitor.blocked && visitor.active && used < settings.visitorAnnualLimit && monthly < settings.memberMonthlyInvitationLimit }
  })
  app.post('/access/check-in', { preHandler: app.requirePermission('access.manage') }, async (request: any, reply) => {
    const body = request.body ?? {}; const now = new Date(); const accessPoint = await point(); let person: any; let invitation: any
    if (body.credentialToken) { person = await prisma.person.findUnique({ where: { credentialToken: body.credentialToken }, include: { member: true } }); if (!person) return reply.code(404).send({ message: 'Credencial não encontrada.' }); if (person.member?.status !== 'ACTIVE') return reply.code(403).send({ message: 'Pessoa não autorizada.' }) } else { const cpf = String(body.cpf || '').replace(/\D/g, ''); const visitor = await prisma.visitor.findFirst({ where: { person: { cpf } }, include: { person: true, invitations: { where: { status: 'SCHEDULED' }, include: { sponsorMember: true } } } }); if (!visitor) return reply.code(404).send({ message: 'Visitante não cadastrado.' }); const settings = await prisma.clubSetting.findFirstOrThrow(); const used = await prisma.accessEvent.count({ where: { personId: visitor.personId, type: 'ENTRY', occurredAt: { gte: new Date(Date.UTC(now.getUTCFullYear(), 0, 1)) } } }); invitation = visitor.invitations.find((item: any) => new Date(item.scheduledDate).toDateString() === now.toDateString()); if (visitor.blocked) return reply.code(403).send({ message: 'Visitante bloqueado.' }); if (!invitation) return reply.code(403).send({ message: 'Sem convite válido para hoje.' }); if (used >= settings.visitorAnnualLimit) return reply.code(403).send({ message: 'Limite anual atingido.' }); const monthly = await prisma.accessEvent.count({ where: { invitation: { sponsorMemberId: invitation.sponsorMemberId }, type: 'ENTRY', occurredAt: { gte: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)) } } }); if (monthly >= settings.memberMonthlyInvitationLimit) return reply.code(403).send({ message: 'Limite mensal do titular atingido.' }); person = visitor.person }
    const recent = await prisma.accessEvent.findFirst({ where: { personId: person.id, type: 'ENTRY', occurredAt: { gte: new Date(Date.now() - 10000) } } }); if (recent) return reply.code(409).send({ message: 'Entrada já registrada recentemente.', event: recent }); const event = await prisma.accessEvent.create({ data: { personId: person.id, accessPointId: accessPoint.id, type: 'ENTRY', method: body.credentialToken ? 'QR_CODE' : 'CPF_SEARCH', invitationId: invitation?.id, registeredByUserId: request.authUser!.id }, include: { person: true, accessPoint: true } }); if (invitation) await prisma.visitorInvitation.update({ where: { id: invitation.id }, data: { status: 'USED', usedAt: now } }); return { message: 'ENTRADA REGISTRADA', event }
  })
  app.post('/access/check-out', { preHandler: app.requirePermission('access.manage') }, async (request: any) => { const person = await prisma.person.findUniqueOrThrow({ where: { id: request.body.personId } }); const accessPoint = await point(); return prisma.accessEvent.create({ data: { personId: person.id, accessPointId: accessPoint.id, type: 'EXIT', method: 'MANUAL', registeredByUserId: request.authUser!.id }, include: { person: true, accessPoint: true } }) })
  app.get('/access/events', { preHandler: app.requirePermission('access.view') }, async () => prisma.accessEvent.findMany({ include: { person: { include: { member: { include: { category: true } } } }, accessPoint: true, registeredBy: true }, orderBy: { occurredAt: 'desc' }, take: 200 }))
  app.get('/access/stats', { preHandler: app.requirePermission('access.view') }, async () => { const since = new Date(); since.setHours(0, 0, 0, 0); const rows = await prisma.accessEvent.findMany({ where: { type: 'ENTRY', occurredAt: { gte: since } }, include: { person: { include: { member: { include: { category: true } }, visitor: true } } } }); return { entries: rows.length, uniquePeople: new Set(rows.map((row) => row.personId)).size, members: rows.filter((row) => row.person.member && row.person.member.category.name !== 'Dependente').length, dependents: rows.filter((row) => row.person.member?.category.name === 'Dependente').length, visitors: rows.filter((row) => row.person.visitor).length } })
}
