// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
import { monthBounds } from '../visitors/quotas.js'

const point = () => prisma.accessPoint.findFirstOrThrow({ where: { active: true } })
const memberInclude = { category: true, titular: { include: { person: true } } }
const todayRange = () => { const n = new Date(); return { now: n, start: new Date(Date.UTC(n.getUTCFullYear(), n.getUTCMonth(), n.getUTCDate())), end: new Date(Date.UTC(n.getUTCFullYear(), n.getUTCMonth(), n.getUTCDate() + 1)) } }

export const accessRoutes: FastifyPluginAsync = async app => {
  app.post('/access/validate-credential', { preHandler: app.requirePermission('access.view') }, async (request: any, reply) => {
    const person = await prisma.person.findUnique({ where: { credentialToken: request.body?.credentialToken }, include: { member: { include: memberInclude } } })
    if (!person) return reply.code(404).send({ message: 'Credencial não encontrada.' }); const member = person.member
    if (!member) return reply.code(403).send({ message: 'Pessoa não autorizada.' }); const dependent = member.category.isDependent || member.category.requiresHolder
    return { person: { id: person.id, fullName: person.fullName, photoPath: person.photoPath, cpf: `${person.cpf.slice(0, 3)}.***.***-**` }, subject: { type: dependent ? 'Dependente' : 'Sócio', status: member.status, category: member.category.name, holderName: dependent ? member.titular?.person.fullName : undefined, memberId: member.id }, allowed: member.status === 'ACTIVE' }
  })
  app.get('/access/visitor/search', { preHandler: app.requirePermission('access.view') }, async (request: any) => { const q = String(request.query?.q || '').trim(); const digits = q.replace(/\D/g, ''); if (!q) return []; return prisma.visitor.findMany({ where: { OR: [{ person: { fullName: { contains: q, mode: 'insensitive' } } }, ...(digits ? [{ person: { cpf: { contains: digits } } }] : [])] }, include: { person: true }, take: 20, orderBy: { person: { fullName: 'asc' } } }) })
  app.get('/access/visitor/:cpf', { preHandler: app.requirePermission('access.view') }, async (request: any, reply) => {
    const cpf = String(request.params.cpf).replace(/\D/g, ''); const visitor = await prisma.visitor.findFirst({ where: { person: { cpf } }, include: { person: true, invitations: { include: { sponsorMember: { include: { person: true, category: true } } }, orderBy: { scheduledDate: 'desc' } } } })
    if (!visitor) return reply.code(404).send({ message: 'Visitante não cadastrado.' }); const { start, end } = todayRange(); const valid = visitor.invitations.find(i => i.status === 'SCHEDULED' && new Date(i.scheduledDate) >= start && new Date(i.scheduledDate) < end); const settings = await prisma.clubSetting.findFirstOrThrow()
    return { visitor: { id: visitor.id, person: { fullName: visitor.person.fullName, cpf: `${cpf.slice(0, 3)}.***.***-**`, phone: visitor.person.phone, city: visitor.person.city }, blocked: visitor.blocked, active: visitor.active }, invitations: valid ? [valid] : [], history: visitor.invitations, annualLimit: settings.visitorAnnualLimit, sponsor: valid?.sponsorMember?.person?.fullName, authorized: Boolean(valid && !visitor.blocked && visitor.active) }
  })
  app.post('/access/check-in', { preHandler: app.requirePermission('access.manage') }, async (request: any, reply) => {
    const body = request.body || {}; const accessPoint = await point(); let person: any; let invitation: any
    if (body.credentialToken) { person = await prisma.person.findUnique({ where: { credentialToken: body.credentialToken }, include: { member: true } }); if (!person) return reply.code(404).send({ message: 'Credencial não encontrada.' }); if (person.member?.status !== 'ACTIVE') return reply.code(403).send({ message: 'Pessoa não autorizada.' }) }
    else { const cpf = String(body.cpf || '').replace(/\D/g, ''); const visitor = await prisma.visitor.findFirst({ where: { person: { cpf } }, include: { person: true } }); if (!visitor) return reply.code(404).send({ message: 'Visitante não cadastrado.' }); if (visitor.blocked) return reply.code(403).send({ message: 'Visitante bloqueado.' }); if (!visitor.active) return reply.code(403).send({ message: 'Visitante inativo.' }); person = visitor.person; const { start, end } = todayRange(); invitation = await prisma.visitorInvitation.findFirst({ where: { visitorId: visitor.id, status: 'SCHEDULED', scheduledDate: { gte: start, lt: end } }, orderBy: { createdAt: 'asc' } }); if (!invitation) return reply.code(403).send({ message: 'Sem convite válido para hoje.' }) }
    const recent = await prisma.accessEvent.findFirst({ where: { personId: person.id, type: 'ENTRY', occurredAt: { gte: new Date(Date.now() - 10000) } } }); if (recent) return reply.code(409).send({ message: 'Entrada já registrada recentemente.', event: recent }); const now = new Date()
    try { const event = await prisma.$transaction(async tx => { let locked: any = null; if (invitation) { await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${invitation.id}, 0))`; locked = await tx.visitorInvitation.findUnique({ where: { id: invitation.id } }); if (!locked || locked.status !== 'SCHEDULED') { const e: any = new Error('Este convite já foi utilizado.'); e.statusCode = 409; throw e } } const created = await tx.accessEvent.create({ data: { personId: person.id, accessPointId: accessPoint.id, type: 'ENTRY', method: body.credentialToken ? 'QR_CODE' : 'CPF_SEARCH', invitationId: locked?.id, registeredByUserId: request.authUser!.id }, include: { person: true, accessPoint: true } }); if (locked) await tx.visitorInvitation.update({ where: { id: locked.id }, data: { status: 'USED', usedAt: now } }); return created }); return { message: 'ENTRADA REGISTRADA', event } } catch (e: any) { return reply.code(e.statusCode || 500).send({ message: e.message || 'Não foi possível registrar a entrada.' }) }
  })
  app.post('/access/check-out', { preHandler: app.requirePermission('access.manage') }, async (request: any) => { const person = await prisma.person.findUniqueOrThrow({ where: { id: request.body.personId } }); const accessPoint = await point(); return prisma.accessEvent.create({ data: { personId: person.id, accessPointId: accessPoint.id, type: 'EXIT', method: 'MANUAL', registeredByUserId: request.authUser!.id }, include: { person: true, accessPoint: true } }) })
  app.get('/access/events', { preHandler: app.requirePermission('access.view') }, async (request: any) => { const from = request.query?.from ? new Date(request.query.from) : new Date(new Date().setHours(0, 0, 0, 0)); const to = request.query?.to ? new Date(`${request.query.to}T23:59:59.999Z`) : new Date(); const q = request.query?.q?.trim(); return prisma.accessEvent.findMany({ where: { type: 'ENTRY', occurredAt: { gte: from, lte: to }, ...(q ? { person: { OR: [{ fullName: { contains: q, mode: 'insensitive' } }, { cpf: { contains: q.replace(/\D/g, '') } }] } } : {}) }, include: { person: { include: { member: { include: { category: true } } } }, accessPoint: true, registeredBy: { include: { person: true } } }, orderBy: { occurredAt: 'desc' }, take: 500 }) })
  app.get('/access/stats', { preHandler: app.requirePermission('access.view') }, async (request: any) => { const now = new Date(); const start = request.query?.from ? new Date(request.query.from) : new Date(new Date().setHours(0, 0, 0, 0)); const end = request.query?.to ? new Date(`${request.query.to}T23:59:59.999Z`) : now; const rows = await prisma.accessEvent.findMany({ where: { type: 'ENTRY', occurredAt: { gte: start, lte: end } }, include: { person: { include: { member: { include: { category: true } }, visitor: true } } } }); const byDay = new Map<string, number>(); for (const row of rows) { const day = new Date(row.occurredAt).toISOString().slice(0, 10); byDay.set(day, (byDay.get(day) || 0) + 1) }; const period = (days: number) => rows.filter(r => new Date(r.occurredAt) >= new Date(now.getTime() - days * 86400000)).length; return { entries: rows.length, uniquePeople: new Set(rows.map(r => r.personId)).size, today: period(1), last2Days: period(2), last7Days: period(7), byDay: [...byDay].map(([date, total]) => ({ date, total })), peakHours: Object.entries(rows.reduce((a: any, r) => { const h = new Date(r.occurredAt).getHours(); a[h] = (a[h] || 0) + 1; return a }, {})).sort((a: any, b: any) => b[1] - a[1]).slice(0, 3) } })
}
