// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'

export const communicationsRoutes: FastifyPluginAsync = async (app) => {
  app.get('/member/me/announcements', { preHandler: app.authenticate }, async (request: any) => { const user = await prisma.user.findUnique({ where: { id: request.authUser.id }, include: { person: { include: { member: true } } } }); if (!user?.person.member) return []; const now = new Date(); return prisma.announcement.findMany({ where: { active: true, startDate: { lte: now }, OR: [{ endDate: null }, { endDate: { gte: now } },], ...(user.person.member.titularMemberId ? {} : {}) }, orderBy: { startDate: 'desc' } }) })
  app.get('/announcements', { preHandler: app.requirePermission('announcements.view') }, async (request: any) => { const now = new Date(); const filter = request.query?.filter; const where: any = {}; if (filter === 'future') where.startDate = { gt: now }; if (filter === 'published') where.AND = [{ startDate: { lte: now } }, { OR: [{ endDate: null }, { endDate: { gte: now } }] }]; if (filter === 'expired') where.endDate = { lt: now }; if (filter === 'inactive') where.active = false; return prisma.announcement.findMany({ where, orderBy: { startDate: 'desc' } }) })
  app.post('/announcements', { preHandler: app.requirePermission('announcements.manage') }, async (request: any, reply) => { const b = request.body ?? {}; if (!b.title || !b.content || !b.startDate) return reply.code(400).send({ message: 'Título, conteúdo e início de publicação são obrigatórios.' }); if (b.endDate && new Date(b.endDate) < new Date(b.startDate)) return reply.code(400).send({ message: 'O fim deve ser posterior ao início.' }); return reply.code(201).send(await prisma.announcement.create({ data: { title: b.title, content: b.content, startDate: new Date(b.startDate), endDate: b.endDate ? new Date(b.endDate) : null, imagePath: b.imagePath || null, audience: b.audience === 'HOLDERS_ONLY' ? 'HOLDERS_ONLY' : 'ALL_MEMBERS', active: b.active !== false, createdByUserId: request.authUser.id } })) })
  app.put('/announcements/:id', { preHandler: app.requirePermission('announcements.manage') }, async (request: any, reply) => { try { const b = request.body ?? {}; return await prisma.announcement.update({ where: { id: request.params.id }, data: { title: b.title, content: b.content, startDate: new Date(b.startDate), endDate: b.endDate ? new Date(b.endDate) : null, imagePath: b.imagePath || null, audience: b.audience, active: b.active } }) } catch { return reply.code(404).send({ message: 'Aviso não encontrado.' }) } })
  app.delete('/announcements/:id', { preHandler: app.requirePermission('announcements.manage') }, async (request: any, reply) => { try { await prisma.announcement.delete({ where: { id: request.params.id } }); return { ok: true } } catch { return reply.code(404).send({ message: 'Aviso não encontrado.' }) } })
  app.post('/announcements/:id/toggle', { preHandler: app.requirePermission('announcements.manage') }, async (request: any, reply) => { const row = await prisma.announcement.findUnique({ where: { id: request.params.id } }); if (!row) return reply.code(404).send({ message: 'Aviso não encontrado.' }); return prisma.announcement.update({ where: { id: row.id }, data: { active: !row.active } }) })
  app.get('/events', { preHandler: app.requirePermission('events.view') }, async () => prisma.clubEvent.findMany({ orderBy: { startDateTime: 'asc' } }))
  app.get('/member/me/events', { preHandler: app.authenticate }, async () => prisma.clubEvent.findMany({ where: { active: true, startDateTime: { gte: new Date() } }, orderBy: { startDateTime: 'asc' } }))
  app.post('/events', { preHandler: app.requirePermission('events.manage') }, async (request: any, reply) => { const b = request.body ?? {}; if (!b.title || !b.description || !b.startDateTime) return reply.code(400).send({ message: 'Título, descrição e data são obrigatórios.' }); return reply.code(201).send(await prisma.clubEvent.create({ data: { title: b.title, description: b.description, location: b.location || null, startDateTime: new Date(b.startDateTime), endDateTime: b.endDateTime ? new Date(b.endDateTime) : null, memberPrice: b.memberPrice ?? null, guestPrice: b.guestPrice ?? null, capacity: b.capacity ?? null, active: b.active !== false, createdByUserId: request.authUser.id } })) })
  app.put('/events/:id', { preHandler: app.requirePermission('events.manage') }, async (request: any, reply) => { try { return await prisma.clubEvent.update({ where: { id: request.params.id }, data: request.body }) } catch { return reply.code(404).send({ message: 'Evento não encontrado.' }) } })
  app.post('/events/:id/toggle', { preHandler: app.requirePermission('events.manage') }, async (request: any, reply) => { const row = await prisma.clubEvent.findUnique({ where: { id: request.params.id } }); if (!row) return reply.code(404).send({ message: 'Evento não encontrado.' }); return prisma.clubEvent.update({ where: { id: row.id }, data: { active: !row.active } }) })
}
