// @ts-nocheck
import type { FastifyPluginAsync } from 'fastify'
import { prisma } from '../../../lib/prisma.js'
export const communicationsRoutes:FastifyPluginAsync=async app=>{
 app.get('/member/me/announcements',{preHandler:app.authenticate},async(req,reply)=>{const u=await prisma.user.findUnique({where:{id:req.authUser!.id},include:{person:{include:{member:true}}}});if(!u?.person.member)return [];const now=new Date();return prisma.announcement.findMany({where:{active:true,startDate:{lte:now},endDate:{gte:now},OR:[{audience:'ALL_MEMBERS'},...(u.person.member?([{audience:'HOLDERS_ONLY'}]):[])]},orderBy:{startDate:'desc'}})})
 app.get('/member/me/events',{preHandler:app.authenticate},async()=>prisma.clubEvent.findMany({where:{active:true,startDateTime:{gte:new Date()}},orderBy:{startDateTime:'asc'}}))
 app.get('/announcements',{preHandler:app.requirePermission('announcements.view')},async()=>prisma.announcement.findMany({orderBy:{startDate:'desc'}}))
 app.post('/announcements',{preHandler:app.requirePermission('announcements.manage')},async(req:any,reply)=>{const b=req.body??{};if(!b.title||!b.content||!b.startDate||!b.endDate)return reply.code(400).send({message:'Título, conteúdo e período são obrigatórios.'});return reply.code(201).send(await prisma.announcement.create({data:{title:b.title,content:b.content,startDate:new Date(b.startDate),endDate:new Date(b.endDate),audience:b.audience==='HOLDERS_ONLY'?'HOLDERS_ONLY':'ALL_MEMBERS',active:b.active!==false,createdByUserId:req.authUser!.id}}))})
 app.put('/announcements/:id',{preHandler:app.requirePermission('announcements.manage')},async(req:any,reply)=>{try{return await prisma.announcement.update({where:{id:req.params.id},data:req.body})}catch{return reply.code(404).send({message:'Aviso não encontrado.'})}})
 app.post('/announcements/:id/toggle',{preHandler:app.requirePermission('announcements.manage')},async(req:any,reply)=>{const a=await prisma.announcement.findUnique({where:{id:req.params.id}});if(!a)return reply.code(404).send({message:'Aviso não encontrado.'});return prisma.announcement.update({where:{id:a.id},data:{active:!a.active}})})
 app.get('/events',{preHandler:app.requirePermission('events.view')},async()=>prisma.clubEvent.findMany({orderBy:{startDateTime:'asc'}}))
 app.post('/events',{preHandler:app.requirePermission('events.manage')},async(req:any,reply)=>{const b=req.body??{};if(!b.title||!b.description||!b.startDateTime)return reply.code(400).send({message:'Título, descrição e data são obrigatórios.'});return reply.code(201).send(await prisma.clubEvent.create({data:{title:b.title,description:b.description,location:b.location||null,startDateTime:new Date(b.startDateTime),endDateTime:b.endDateTime?new Date(b.endDateTime):null,memberPrice:b.memberPrice??null,guestPrice:b.guestPrice??null,capacity:b.capacity??null,active:b.active!==false,createdByUserId:req.authUser!.id}}))})
 app.put('/events/:id',{preHandler:app.requirePermission('events.manage')},async(req:any,reply)=>{try{return await prisma.clubEvent.update({where:{id:req.params.id},data:req.body})}catch{return reply.code(404).send({message:'Evento não encontrado.'})}})
 app.post('/events/:id/toggle',{preHandler:app.requirePermission('events.manage')},async(req:any,reply)=>{const e=await prisma.clubEvent.findUnique({where:{id:req.params.id}});if(!e)return reply.code(404).send({message:'Evento não encontrado.'});return prisma.clubEvent.update({where:{id:e.id},data:{active:!e.active}})})
}
