import { useEffect, useState } from 'react'
import { apiRequest } from '../../../api/client'
import { dateLabel, dateTimeLabel } from '../ui/format'
import './member-history.css'

const auth = () => ({ headers: { Authorization: `Bearer ${sessionStorage.getItem('cisne.accessToken') || ''}` } })
const reservationStatus: Record<string, string> = { REQUESTED: 'Solicitada', APPROVED: 'Confirmada', REJECTED: 'Recusada', CANCELLED: 'Cancelada', COMPLETED: 'Concluída' }
const invitationStatus: Record<string, string> = { SCHEDULED: 'Válido', USED: 'Utilizado', CANCELLED: 'Cancelado', EXPIRED: 'Expirado' }
const money = (value: any) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

export function MemberHistoryTabs({ memberId }: { memberId: string }) {
  const [tab, setTab] = useState<'invitations' | 'reservations' | 'access'>('invitations')
  const [data, setData] = useState<any>(null)
  const [error, setError] = useState('')
  useEffect(() => { setData(null); setError(''); apiRequest<any>(`/api/members/${memberId}/activity`, { headers: auth().headers }).then(setData).catch(e => setError(e.message)) }, [memberId])
  const tabs = [{ key: 'invitations' as const, label: 'Convites', count: data?.invitations?.length }, { key: 'reservations' as const, label: 'Reservas', count: data?.reservations?.length }, { key: 'access' as const, label: 'Acessos', count: data?.accessEvents?.length }]
  return <section className="member-history-card record-card"><div className="member-history-heading"><div><span className="eyebrow">HISTÓRICO DO GRUPO</span><h2>Atividades do sócio</h2>{data?.titular && <p>Informações compartilhadas pelo titular <strong>{data.titular.fullName}</strong>.</p>}</div></div>{error && <p className="form-error">{error}</p>}<div className="member-history-tabs" role="tablist" aria-label="Histórico do grupo familiar">{tabs.map(item => <button key={item.key} className={tab === item.key ? 'active' : ''} role="tab" aria-selected={tab === item.key} onClick={() => setTab(item.key)}>{item.label}<span>{item.count ?? '—'}</span></button>)}</div>{!data && !error && <p className="empty-state">Carregando histórico…</p>}{data && tab === 'invitations' && <div className="member-history-list">{data.invitations.length ? data.invitations.map((item: any) => <article className="member-history-item" key={item.id}><div><strong>{item.visitor?.person?.fullName || 'Visitante'}</strong><span>Emitido em {dateLabel(item.createdAt)} · {invitationStatus[item.status] || item.status}</span><small>Por {item.sponsorMember?.person?.fullName || 'membro do grupo'}{item.usedAt ? ` · Entrada em ${dateTimeLabel(item.usedAt)}` : ''}</small></div><strong className="member-history-value">{item.status === 'USED' ? 'Utilizado' : invitationStatus[item.status] || item.status}</strong></article>) : <p className="empty-state">Nenhum convite registrado para este grupo.</p>}</div>}{data && tab === 'reservations' && <div className="member-history-list">{data.reservations.length ? data.reservations.map((item: any) => <article className="member-history-item" key={item.id}><div><strong>{item.space?.name || 'Espaço'}</strong><span>{dateLabel(item.reservationDate)}{item.startTime ? ` · ${item.startTime}${item.endTime ? `–${item.endTime}` : ''}` : ' · Dia inteiro'}</span><small>Solicitada por {item.member?.person?.fullName || 'membro do grupo'}</small></div><strong className="member-history-value">{reservationStatus[item.status] || item.status}<small>{money(item.totalAmount)}</small></strong></article>) : <p className="empty-state">Nenhuma reserva registrada para este grupo.</p>}</div>}{data && tab === 'access' && <div className="member-history-list">{data.accessEvents.length ? data.accessEvents.map((item: any) => <article className="member-history-item" key={item.id}><div><strong>{item.person?.fullName || 'Associado'}</strong><span>{dateTimeLabel(item.occurredAt)} · {item.accessPoint?.name || 'Ponto de acesso'}</span><small>{item.invitation ? `Entrada com convite de ${item.invitation.sponsorMember?.person?.fullName || 'membro do grupo'}` : `Método: ${item.method}`}</small></div><strong className="member-history-value">Entrada</strong></article>) : <p className="empty-state">Nenhum acesso registrado para este grupo.</p>}</div>}</section>
}
