import { useEffect, useState } from 'react'
import { ArrowLeft } from 'lucide-react'
import { apiRequest } from '../../../api/client'
const auth = () => ({ headers: { Authorization: `Bearer ${sessionStorage.getItem('cisne.accessToken') || ''}` } })
export function MemberCategoriesPage({ onBack }: { onBack: () => void }) {
  const [rows, setRows] = useState<any[]>([]), [name, setName] = useState(''), [dependent, setDependent] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState(''), [saving, setSaving] = useState(false)
  const load = () => { apiRequest<any[]>('/api/member-categories', auth()).then(setRows).catch(e => setError(e.message)) }
  useEffect(() => { load() }, [])
  const create = async () => { if (!name.trim()) { setError('Informe o nome da modalidade.'); return }; setSaving(true); setError(''); try { await apiRequest('/api/member-categories', { method: 'POST', headers: { ...auth().headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ name, isDependent: dependent, requiresHolder: dependent }) }); setName(''); setDependent(false); setMessage('Categoria cadastrada.'); load() } catch (e: any) { setError(e.message) } finally { setSaving(false) } }
  return <main className="members-page"><button className="text-button" onClick={onBack}><ArrowLeft size={16} /> Painel</button><span className="eyebrow">Administração</span><h1>Tipos de Sócio</h1>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}<section className="record-card"><div className="category-form"><label>Nome da modalidade<input required placeholder="Nome da modalidade" value={name} onChange={e => setName(e.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={dependent} onChange={e => setDependent(e.target.checked)} /> É dependente / exige titular</label><button className="login-button" disabled={saving} onClick={create}>Criar categoria</button></div></section><section className="members-table-wrap" role="region" aria-label="Categorias" tabIndex={0}><table className="members-table"><thead><tr><th>Nome</th><th>Natureza</th><th>Status</th><th>Ação</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.isDependent || row.requiresHolder ? 'Dependente' : 'Titular'}</td><td><span className={`status-badge ${row.active ? 'ACTIVE' : 'INACTIVE'}`}>{row.active ? 'Ativo' : 'Inativo'}</span></td><td><button className="member-row-action" disabled={saving} onClick={async () => { setSaving(true); setError(''); try { await apiRequest(`/api/member-categories/${row.id}`, { method: 'PUT', headers: { ...auth().headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...row, active: !row.active }) }); setMessage('Categoria atualizada.'); load() } catch (e: any) { setError(e.message) } finally { setSaving(false) } }}>{row.active ? 'Desativar' : 'Ativar'}</button></td></tr>)}</tbody></table></section></main>
}
