import { ArrowLeft, Ban, Edit3, Eye, Plus, Save, XCircle } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { apiRequest } from '../../../api/client'
import { Feedback } from '../ui/Feedback'
import { Modal } from '../ui/Modal'
import { dateLabel, invitationStatus } from '../ui/format'
import { useAuth } from '../auth/AuthProvider'
import { hasPermission } from '../auth/permissions'
import '../communications/community.css'

const auth = () => ({ headers: { Authorization: `Bearer ${sessionStorage.getItem('cisne.accessToken') || ''}` } })
const empty = { fullName: '', cpf: '', phone: '', city: '', email: '', birthDate: '' }
const currentMonth = () => new Date().toISOString().slice(0, 7)

export function VisitorsPage({ onBack }: { onBack: () => void }) {
  const { user } = useAuth(); const canManage = hasPermission(user, 'visitors.manage')
  const [visitors, setVisitors] = useState<any[]>([]), [members, setMembers] = useState<any[]>([]), [invitations, setInvitations] = useState<any[]>([]), [summary, setSummary] = useState<any>({})
  const [show, setShow] = useState(false), [inviteFor, setInviteFor] = useState<any>(null), [editing, setEditing] = useState<any>(null), [history, setHistory] = useState<any>(null), [profile, setProfile] = useState<any>(null)
  const [message, setMessage] = useState(''), [error, setError] = useState(''), [saving, setSaving] = useState(false), [loading, setLoading] = useState(true), [query, setQuery] = useState(''), [status, setStatus] = useState(''), [month, setMonth] = useState(currentMonth())
  const [form, setForm] = useState(empty), [invite, setInvite] = useState({ sponsorMemberId: '', scheduledDate: '' })
  const load = async () => { setLoading(true); try { const [vs, inv] = await Promise.all([apiRequest<any[]>(`/api/visitors?q=${encodeURIComponent(query)}${status ? `&status=${status}` : ''}`, auth()), apiRequest<any>(`/api/invitations?month=${month}`, auth())]); setVisitors(vs); setInvitations(inv.rows || []); setSummary(inv.summary || {}) } catch (e: any) { setError(e.message) } finally { setLoading(false) } }
  useEffect(() => { void load(); if (canManage) apiRequest<any[]>('/api/members', auth()).then(setMembers).catch(e => setError(e.message)) }, [query, status, month, canManage])
  const saveVisitor = async (event: FormEvent) => { event.preventDefault(); setError(''); setSaving(true); try { await apiRequest(editing ? `/api/visitors/${editing.id}` : '/api/visitors', { method: editing ? 'PUT' : 'POST', ...auth(), body: JSON.stringify(form) }); setShow(false); setEditing(null); setForm(empty); setMessage(editing ? 'Visitante atualizado.' : 'Visitante cadastrado.'); await load() } catch (e: any) { setError(e.message) } finally { setSaving(false) } }
  const block = async (visitor: any) => { setSaving(true); try { await apiRequest(`/api/visitors/${visitor.id}/block`, { method: 'POST', ...auth() }); setMessage(visitor.blocked ? 'Visitante desbloqueado.' : 'Visitante bloqueado.'); await load() } catch (e: any) { setError(e.message) } finally { setSaving(false) } }
  const createInvite = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await apiRequest('/api/invitations', { method: 'POST', ...auth(), body: JSON.stringify({ visitorId: inviteFor.id, ...invite }) }); setInviteFor(null); setInvite({ sponsorMemberId: '', scheduledDate: '' }); setMessage('Convite criado.'); await load() } catch (e: any) { setError(e.message) } finally { setSaving(false) } }
  const cancelInvite = async (id: string) => { if (!window.confirm('Tem certeza de que deseja cancelar este convite?')) return; try { await apiRequest(`/api/invitations/${id}/cancel`, { method: 'POST', ...auth() }); setMessage('Convite cancelado.'); await load() } catch (e: any) { setError(e.message) } }
  const openEdit = (v: any) => { setEditing(v); setForm({ fullName: v.person.fullName, cpf: v.person.cpf, phone: v.person.phone || '', city: v.person.city || '', email: v.person.email || '', birthDate: v.person.birthDate ? v.person.birthDate.slice(0, 10) : '' }); setShow(true) }
  return <main className="community-page"><button className="finance-back" onClick={onBack}><ArrowLeft size={18} /> Voltar ao painel</button><span className="eyebrow">Gestão administrativa</span><h1>Visitantes e convites</h1><Feedback error={error} message={message} />
    <div className="section-heading"><h2>Visitantes</h2>{canManage && <button className="btn btn-primary" onClick={() => { setEditing(null); setForm(empty); setShow(true) }}><Plus size={18} /> Novo visitante</button>}</div>
    <div className="filter-bar"><label>Pesquisar nome, CPF ou telefone<input placeholder="Pesquisar visitante" value={query} onChange={e => setQuery(e.target.value)} /></label><label>Situação<select value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos</option><option value="ACTIVE">Ativos</option><option value="BLOCKED">Bloqueados</option><option value="INACTIVE">Inativos</option></select></label><strong>Total: {visitors.length}</strong></div>
    <div className="table-scroll"><table className="data-table"><thead><tr><th>Nome</th><th>CPF</th><th>Telefone</th><th>Cidade</th><th>Situação</th><th>Visitas no ano</th><th>Ações</th></tr></thead><tbody>{visitors.map(v => <tr key={v.id}><td><strong>{v.person.fullName}</strong></td><td>{v.person.cpf}</td><td>{v.person.phone || '—'}</td><td>{v.person.city || '—'}</td><td><span className={`status-badge ${v.blocked ? 'SUSPENDED' : v.active ? 'ACTIVE' : 'INACTIVE'}`}>{v.blocked ? 'Bloqueado' : v.active ? 'Ativo' : 'Inativo'}</span></td><td>{v.visitsThisYear}</td><td><div className="row-actions"><button className="btn btn-secondary" onClick={() => setProfile(v)}><Eye size={16} /> Ver</button>{canManage && <><button className="btn btn-edit" onClick={() => openEdit(v)}><Edit3 size={16} /> Editar</button><button className="btn btn-secondary" onClick={() => block(v)}><Ban size={16} /> {v.blocked ? 'Desbloquear' : 'Bloquear'}</button><button className="btn btn-primary" disabled={v.blocked || !v.active} onClick={() => setInviteFor(v)}>Criar convite</button></>}<button className="btn btn-secondary" onClick={() => setHistory(v)}>Histórico</button></div></td></tr>)}</tbody></table>{loading && <p className="empty-state">Carregando…</p>}{!loading && !visitors.length && <p className="empty-state">Nenhum visitante encontrado.</p>}</div>
    <section className="member-section"><div className="section-heading"><div><span className="eyebrow">PERÍODO</span><h2>Convites — {month.split('-').reverse().join('/')}</h2></div><label>Mês<input type="month" value={month} onChange={e => setMonth(e.target.value)} /></label></div><div className="access-dashboard"><div><span>Convites no mês</span><strong>{summary.total || 0}</strong></div><div><span>Utilizados</span><strong>{summary.used || 0}</strong></div><div><span>Pendentes/Válidos</span><strong>{summary.pending || 0}</strong></div><div><span>Cancelados</span><strong>{summary.cancelled || 0}</strong></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Visitante</th><th>Sócio convidante</th><th>Categoria</th><th>Data da visita</th><th>Status</th><th>Cota mensal</th><th>Ações</th></tr></thead><tbody>{invitations.map(i => <tr key={i.id}><td>{i.visitor?.person?.fullName}</td><td>{i.sponsorMember?.person?.fullName}</td><td>{i.sponsorMember?.category?.name}</td><td>{dateLabel(i.scheduledDate)}</td><td>{invitationStatus[i.status] || i.status}</td><td>—</td><td>{canManage && i.status === 'SCHEDULED' && <button className="btn btn-secondary" onClick={() => cancelInvite(i.id)}><XCircle size={16} /> Cancelar</button>}</td></tr>)}</tbody></table>{!invitations.length && <p className="empty-state">Nenhum convite no período.</p>}</div></section>
    {show && <Modal title={editing ? 'Editar visitante' : 'Novo visitante'} onClose={() => !saving && setShow(false)}><form className="ui-form" onSubmit={saveVisitor}><Feedback error={error} />{(['fullName', 'cpf', 'phone', 'city', 'email', 'birthDate'] as const).map(field => <label key={field}>{{ fullName: 'Nome completo', cpf: 'CPF', phone: 'Telefone', city: 'Cidade', email: 'E-mail (opcional)', birthDate: 'Nascimento (opcional)' }[field]}<input required={['fullName', 'cpf', 'phone', 'city'].includes(field)} type={field === 'birthDate' ? 'date' : field === 'email' ? 'email' : 'text'} value={form[field]} onChange={e => setForm({ ...form, [field]: e.target.value })} /></label>)}<div className="form-actions"><button type="button" className="btn btn-secondary" onClick={() => setShow(false)}>Cancelar</button><button className="btn btn-primary" disabled={saving}><Save size={16} /> Salvar</button></div></form></Modal>}
    {inviteFor && <Modal title="Criar convite" onClose={() => setInviteFor(null)}><p>Visitante: <strong>{inviteFor.person.fullName}</strong></p><form className="ui-form" onSubmit={createInvite}><Feedback error={error} /><label>Sócio convidante<select required value={invite.sponsorMemberId} onChange={e => setInvite({ ...invite, sponsorMemberId: e.target.value })}><option value="">Selecione</option>{members.filter(m => m.status === 'ACTIVE').map(m => <option key={m.id} value={m.id}>{m.person.fullName} · {m.category.name}</option>)}</select></label><small>A elegibilidade e a cota são validadas novamente pelo servidor.</small><label>Data da visita<input required type="date" value={invite.scheduledDate} onChange={e => setInvite({ ...invite, scheduledDate: e.target.value })} /></label><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={() => setInviteFor(null)}>Cancelar</button><button className="btn btn-primary" disabled={saving}>Salvar convite</button></div></form></Modal>}
    {history && <Modal title="Histórico de convites" onClose={() => setHistory(null)}><h3>{history.person.fullName}</h3>{history.invitations?.length ? history.invitations.map((i: any) => <article className="payment-entry" key={i.id}><strong>{dateLabel(i.scheduledDate)} · {invitationStatus[i.status] || i.status}</strong><p>Sócio: {i.sponsorMember?.person?.fullName || 'Não informado'}</p></article>) : <p>Nenhum convite cadastrado.</p>}</Modal>}
    {profile && <Modal title="Ficha do visitante" onClose={() => setProfile(null)}><h3>{profile.person.fullName}</h3><p>CPF: {profile.person.cpf}</p><p>Telefone: {profile.person.phone || '—'} · Cidade: {profile.person.city || '—'}</p><p>E-mail: {profile.person.email || '—'}</p><p>Situação: {profile.blocked ? 'Bloqueado' : profile.active ? 'Ativo' : 'Inativo'}</p><p>Visitas utilizadas no ano: {profile.visitsThisYear}</p></Modal>}
  </main>
}
